package br.unb.cic.rv.builder;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Emits the {@code mop/Coverage.java} runtime class source consumed by
 * {@link MonitorBuilder}. The backing store is
 * {@link java.util.concurrent.ConcurrentHashMap#newKeySet()} so concurrent
 * method entries never drop events (INV-INS-23).
 *
 * <p>The emitted class reproduces the API of the legacy {@code Coverage.aj}'s
 * companion runtime:
 * <ul>
 *   <li>{@code void log(String signature)} — record that the signature ran.</li>
 *   <li>{@code int size()} — number of distinct signatures observed.</li>
 *   <li>{@code Iterable<String> seen()} — snapshot (weakly consistent) of
 *       the set, used by {@code CoverageTracker}.</li>
 * </ul>
 *
 * <p>Spec-set agnostic — the Coverage class is identical whether the MOP
 * overlay comes from JCA or Generic specs.
 */
public final class CoverageSourceEmitter {

    public static final String COVERAGE_PACKAGE = "mop";
    public static final String COVERAGE_CLASS = "Coverage";

    private CoverageSourceEmitter() {}

    public static Path emit(Path outputDir) throws IOException {
        Path dir = outputDir.resolve(COVERAGE_PACKAGE);
        Files.createDirectories(dir);
        Path file = dir.resolve(COVERAGE_CLASS + ".java");
        Files.writeString(file, sourceText());
        return file;
    }

    static String sourceText() {
        return "// Generated by rvsec-instrumentation-dexlib2 CoverageSourceEmitter — DO NOT EDIT.\n"
                + "package " + COVERAGE_PACKAGE + ";\n\n"
                + "import android.util.Log;\n"
                + "import java.util.Set;\n"
                + "import java.util.concurrent.ConcurrentHashMap;\n\n"
                + "public final class " + COVERAGE_CLASS + " {\n"
                + "    private static final String TAG = \"RVSEC-COV\";\n"
                + "    // INV-INS-23: thread-safe lock-free set so concurrent method\n"
                + "    // entries never drop events under monkey --concurrent-threads or\n"
                + "    // coroutine-heavy apps.\n"
                + "    private static final Set<String> SEEN = ConcurrentHashMap.newKeySet();\n\n"
                + "    private " + COVERAGE_CLASS + "() {}\n\n"
                + "    public static void log(String signature) {\n"
                + "        if (SEEN.add(signature)) {\n"
                + "            Log.i(TAG, signature);\n"
                + "        }\n"
                + "    }\n\n"
                + "    public static int size() {\n"
                + "        return SEEN.size();\n"
                + "    }\n\n"
                + "    public static Iterable<String> seen() {\n"
                + "        return SEEN;\n"
                + "    }\n"
                + "}\n";
    }
}
