package br.unb.cic.rvsec.crysl.core;

/**
 * The JUnit tag names that the CI workflow refers to by name, in the one module every other module
 * of this component depends on.
 *
 * <p>Why this is here and not beside the tests that use it. Two test classes in two different
 * modules carry {@code oracle-dependent} — {@code RoundTripGateTest} in {@code rvsec-crysl-mop},
 * which needs {@code android.jar}, and most of {@code rvsec-crysl-crysl}, which needs the upstream
 * CrySL rules — and the CI step excludes the tag by name. Written as a literal in each place, the
 * name would exist as three independent strings that must agree. Nothing would fail if two of them
 * drifted: a tag that no longer matches excludes nothing, so the excluded half would quietly start
 * running in CI, fail on a missing corpus, and the fix would look like "the exclusion is broken"
 * rather than "the name moved". Or worse, the rename lands on the workflow side and the CI green
 * silently narrows.
 *
 * <p>This class lives in {@code src/test} and reaches the other modules through the
 * {@code test-jar} artifact of {@code rvsec-crysl-core}: a tag name is a test concern and does not
 * belong on the production classpath. {@code ReactorBuildIT} asserts the workflow text against
 * {@link #ORACLE_DEPENDENT}, so the workflow is the third holder of the name and it is checked
 * against this constant rather than against a copy of it.
 */
public final class CiTags {

    /**
     * Every test that reads an input from outside this git checkout: the upstream CrySL rules in
     * {@code rvsec-cognicrypt}, {@code android.jar} from {@code $ANDROID_HOME}, or a monitor
     * regenerated by {@code rv-monitor-generator}. CI excludes it and declares that it does.
     */
    public static final String ORACLE_DEPENDENT = "oracle-dependent";

    private CiTags() {
    }
}
