// Generated by rvsec-instrumentation-dexlib2 StampSourceEmitter — DO NOT EDIT.
package mop;

import android.os.Build;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;
import android.view.accessibility.AccessibilityEvent;
import android.view.accessibility.AccessibilityNodeInfo;
import android.view.accessibility.AccessibilityNodeProvider;

import java.util.HashMap;
import java.util.Map;
import java.util.WeakHashMap;

/**
 * Handler stamp: writes the class name of a view's click handler into the
 * extras of the view's {@link AccessibilityNodeInfo}, under
 * {@value #KEY_CLICK} and {@value #KEY_LONG_CLICK}, so a client reading the
 * tree through {@code UiAutomation} learns which handler sits behind a node.
 *
 * <p>The weaver rewrites each call site of {@code View.setOnClickListener},
 * {@code View.setOnLongClickListener} and {@code View.setAccessibilityDelegate}
 * into a call to the static method of the same name here. Each method performs
 * the original call exactly once and then updates the stamp; the stamp logic
 * runs inside {@code catch (Throwable)}, so it never throws into the app. The
 * stamp emits no monitor event.
 *
 * <p>Compose nodes are virtual and have no listener call to rewrite; for them
 * the weaver calls {@link #composeNode} after Compose has populated each node.
 *
 * <p>Every change of a stamp is logged under the tag {@value #TAG}, which lets
 * the stamp be verified from logcat alone.
 */
public final class RvsecStamp {

    public static final String TAG = "RVSEC-BIND";
    public static final String KEY_CLICK = "rvsec.click";
    public static final String KEY_LONG_CLICK = "rvsec.longClick";

    /**
     * View → its stamp delegate, read below API 29 only: there
     * {@code View.getAccessibilityDelegate()} does not exist, so the installed
     * delegate cannot be read back from the view.
     */
    private static final Map<View, Delegate> PRE29 = new WeakHashMap<View, Delegate>();

    private RvsecStamp() {}

    public static void setOnClickListener(View v, View.OnClickListener l) {
        v.setOnClickListener(l);
        try {
            stamp(v, KEY_CLICK, "click", l);
        } catch (Throwable ignored) {
            // The stamp is an observation; the app's call already happened.
        }
    }

    public static void setOnLongClickListener(View v, View.OnLongClickListener l) {
        v.setOnLongClickListener(l);
        try {
            stamp(v, KEY_LONG_CLICK, "longClick", l);
        } catch (Throwable ignored) {
            // The stamp is an observation; the app's call already happened.
        }
    }

    /**
     * Install {@code d} as the app's delegate of {@code v}. On a stamped view,
     * {@code d} is chained behind the stamp delegate instead of replacing it,
     * so a delegate set after the listener does not erase the stamp.
     */
    public static void setAccessibilityDelegate(View v, View.AccessibilityDelegate d) {
        Delegate sd = null;
        try {
            sd = installed(v);
            if (sd != null && d != sd) {
                sd.app = d;
            }
        } catch (Throwable ignored) {
            sd = null;
        }
        v.setAccessibilityDelegate(sd != null ? sd : d);
    }

    /**
     * Record the class of {@code listener} under {@code key}, installing the
     * stamp delegate on the first non-null listener. From API 29 the delegate
     * the view already carries becomes the chained app delegate; below 29 it
     * cannot be read, and the stamp delegate replaces it.
     */
    static void stamp(View v, String key, String kind, Object listener) {
        String cls = listener == null ? null : listener.getClass().getName();
        Delegate sd = installed(v);
        if (sd == null) {
            if (cls == null) {
                return;
            }
            View.AccessibilityDelegate app =
                    Build.VERSION.SDK_INT >= 29 ? v.getAccessibilityDelegate() : null;
            sd = new Delegate(app);
            v.setAccessibilityDelegate(sd);
            if (Build.VERSION.SDK_INT < 29) {
                synchronized (PRE29) {
                    PRE29.put(v, sd);
                }
            }
        }
        String prev = sd.put(key, cls);
        if (cls == null ? prev != null : !cls.equals(prev)) {
            log(v, kind, cls);
        }
    }

    static Delegate installed(View v) {
        if (Build.VERSION.SDK_INT >= 29) {
            View.AccessibilityDelegate d = v.getAccessibilityDelegate();
            return d instanceof Delegate ? (Delegate) d : null;
        }
        synchronized (PRE29) {
            return PRE29.get(v);
        }
    }

    private static void log(View v, String kind, String handler) {
        CharSequence a11y = Build.VERSION.SDK_INT >= 23 ? v.getAccessibilityClassName() : null;
        Log.i(TAG, "view kind=" + kind
                + " node=" + (a11y != null ? a11y : v.getClass().getName())
                + " viewClass=" + v.getClass().getName()
                + " id=" + idName(v)
                + " handler=" + (handler == null ? "-" : handler)
                + " obj=" + Integer.toHexString(System.identityHashCode(v)));
    }

    private static String idName(View v) {
        int id = v.getId();
        if (id == View.NO_ID) {
            return "-";
        }
        try {
            return v.getResources().getResourceName(id);
        } catch (Throwable t) {
            return "0x" + Integer.toHexString(id);
        }
    }

    /**
     * Compose node id → the {@code "click|longClick"} stamp last logged for it,
     * so a node populated again with the same handlers logs nothing.
     */
    private static final Map<Integer, String> COMPOSE_LOGGED = new HashMap<Integer, String>();
    /** {@code class#member} → the reflected member, or {@link #MISSING}. */
    private static final Map<String, Object> MEMBERS = new HashMap<String, Object>();
    private static final Object MISSING = new Object();

    /**
     * Stamp a Compose virtual node. The weaver calls this right after Compose's
     * accessibility delegate has populated {@code infoCompat}
     * ({@code AccessibilityNodeInfoCompat}) from {@code semanticsNode}
     * ({@code SemanticsNode}); both are typed {@code Object} because this class
     * compiles against {@code android.jar} alone, and everything else is read
     * by reflection.
     *
     * <p>The handler is found through the node's own (unmerged) semantics, in
     * two steps (see {@link #composeHandler}). The node step goes from the
     * {@code OnClick} / {@code OnLongClick} action a clickable modifier
     * registers to that modifier node, which holds the app's lambda in
     * {@code onClick} / {@code onLongClick}; a toggleable node's
     * {@code onClick} is Compose's own wrapper, so its {@code onValueChange} is
     * read instead. When the action does not lead to a modifier node, as with
     * an app's own {@code semantics { onClick(...) }}, the action lambda itself
     * is the handler. The Material step then looks through a Material
     * component's own lambda around the app's callback, such as Checkbox's
     * {@code { onCheckedChange(!checked) }}.
     */
    public static void composeNode(Object infoCompat, Object semanticsNode) {
        try {
            composeStamp(infoCompat, semanticsNode);
        } catch (Throwable ignored) {
            // The stamp is an observation; the node is already populated.
        }
    }

    private static void composeStamp(Object infoCompat, Object node) throws Exception {
        AccessibilityNodeInfo info = (AccessibilityNodeInfo) call(infoCompat, "unwrap");
        if (info == null) {
            return;
        }
        Object config = call(node, "getUnmergedConfig$ui_release");
        if (config == null) {
            config = read(node, "unmergedConfig");
        }
        if (config == null) {
            return;
        }
        Class<?> actions = Class.forName("androidx.compose.ui.semantics.SemanticsActions",
                false, node.getClass().getClassLoader());
        Object instance = actions.getField("INSTANCE").get(null);
        String click = composeHandler(config, call(instance, "getOnClick"), "onClick");
        String longClick = composeHandler(config, call(instance, "getOnLongClick"), "onLongClick");

        Bundle extras = info.getExtras();
        if (click != null) {
            extras.putString(KEY_CLICK, click);
        } else {
            extras.remove(KEY_CLICK);
        }
        if (longClick != null) {
            extras.putString(KEY_LONG_CLICK, longClick);
        } else {
            extras.remove(KEY_LONG_CLICK);
        }
        if (click == null && longClick == null) {
            return;
        }
        Object id = call(node, "getId");
        String stamp = click + "|" + longClick;
        synchronized (COMPOSE_LOGGED) {
            if (stamp.equals(COMPOSE_LOGGED.get(id))) {
                return;
            }
            if (COMPOSE_LOGGED.size() > 4096) {
                COMPOSE_LOGGED.clear();
            }
            COMPOSE_LOGGED.put((Integer) id, stamp);
        }
        android.graphics.Rect bounds = new android.graphics.Rect();
        info.getBoundsInScreen(bounds);
        String idName = info.getViewIdResourceName();
        Log.i(TAG, "compose kind=" + (click != null ? "click" : "longClick")
                + " node=" + info.getClassName()
                + " semanticsId=" + id
                + " id=" + (idName == null ? "-" : idName)
                + " bounds=" + bounds.toShortString()
                + " handler=" + (click != null ? click : longClick)
                + (click != null && longClick != null ? " longClickHandler=" + longClick : ""));
    }

    /**
     * The handler class behind the action stored under {@code key} in
     * {@code config} ({@code SemanticsConfiguration}), or {@code null} when the
     * node carries no such action.
     *
     * <p>Node step. The action lambda captures the modifier node, and how it
     * does depends on how the foundation library was compiled: a kotlinc
     * lambda class holds the node as its outer instance, in {@code this$0};
     * from foundation 1.9 the lambda is an invokedynamic that D8 desugars into
     * {@code AbstractClickableNode$$ExternalSyntheticLambdaN}, which holds the
     * node as its first capture, in {@code f$0}. {@code this$0} is taken as
     * found, because in older foundation releases its node can be
     * {@code ClickableSemanticsNode}, which is not an {@code AbstractClickableNode}.
     * {@code f$0} is positional, the first capture of any D8 lambda, an app's
     * own {@code semantics} lambda included, so it is taken only when it holds
     * an {@code AbstractClickableNode}, the base class of every foundation 1.9
     * clickable node. From the node the handler is its {@code field}, or its
     * {@code onValueChange} for a toggleable node's click; with no node, or
     * when that field is null, the handler is the action lambda.
     *
     * <p>Material step. The handler found by the node step, the action lambda
     * included, passes through {@link #materialUnwrap} once.
     */
    private static String composeHandler(Object config, Object key, String field)
            throws Exception {
        if (key == null || !Boolean.TRUE.equals(call(config, "contains", key))) {
            return null;
        }
        Object action = call(config, "get", key);
        Object fn = action == null ? null : call(action, "getAction");
        if (fn == null) {
            return null;
        }
        Object owner = read(fn, "this$0");
        if (owner == null) {
            Object capture = read(fn, "f$0");
            if (capture != null
                    && isA(capture, "androidx.compose.foundation.AbstractClickableNode")) {
                owner = capture;
            }
        }
        Object handler = null;
        if (owner != null) {
            if ("onClick".equals(field) && isA(owner,
                    "androidx.compose.foundation.selection.ToggleableNode")) {
                handler = read(owner, "onValueChange");
            }
            if (handler == null) {
                handler = read(owner, field);
            }
        }
        if (handler == null) {
            handler = fn;
        }
        return materialUnwrap(handler).getClass().getName();
    }

    /**
     * The app's function behind a Material component's own wrapper lambda, or
     * {@code handler} itself. Some Material components hand the foundation
     * modifier a lambda of their own that calls the app's callback, as
     * Checkbox's {@code { onCheckedChange(!checked) }}. Such a wrapper is
     * recognised by shape, since its class name depends on the compiler: its
     * class is in {@code androidx.compose.material*} and declares exactly one
     * non-static field typed as a {@code kotlin.jvm.functions.Function*}
     * interface (kotlinc lambdas extend {@code kotlin.jvm.internal.Lambda} and
     * D8 lambdas extend {@code Object}, so the captures are on the class
     * itself). That field's value is returned when it is non-null and its
     * class is outside {@code androidx.}; a library function keeps the
     * wrapper, and the step is applied once, never along a chain.
     */
    private static Object materialUnwrap(Object handler) throws Exception {
        Class<?> cls = handler.getClass();
        if (!cls.getName().startsWith("androidx.compose.material")) {
            return handler;
        }
        String k = cls.getName() + "#materialFn";
        Object f;
        synchronized (MEMBERS) {
            f = MEMBERS.get(k);
        }
        if (f == null) {
            f = MISSING;
            for (java.lang.reflect.Field candidate : cls.getDeclaredFields()) {
                if (!java.lang.reflect.Modifier.isStatic(candidate.getModifiers())
                        && candidate.getType().getName()
                                .startsWith("kotlin.jvm.functions.Function")) {
                    if (f != MISSING) {
                        f = MISSING;
                        break;
                    }
                    f = candidate;
                }
            }
            if (f != MISSING) {
                ((java.lang.reflect.Field) f).setAccessible(true);
            }
            synchronized (MEMBERS) {
                MEMBERS.put(k, f);
            }
        }
        if (f == MISSING) {
            return handler;
        }
        Object fn = ((java.lang.reflect.Field) f).get(handler);
        return fn == null || fn.getClass().getName().startsWith("androidx.") ? handler : fn;
    }

    private static boolean isA(Object o, String className) {
        for (Class<?> c = o.getClass(); c != null; c = c.getSuperclass()) {
            if (c.getName().equals(className)) {
                return true;
            }
        }
        return false;
    }

    /** Invoke the public method {@code name} of {@code target}; {@code null} when absent. */
    private static Object call(Object target, String name, Object... args) throws Exception {
        Class<?> cls = target.getClass();
        String k = cls.getName() + "#" + name + "/" + args.length;
        Object m;
        synchronized (MEMBERS) {
            m = MEMBERS.get(k);
        }
        if (m == null) {
            m = MISSING;
            for (java.lang.reflect.Method candidate : cls.getMethods()) {
                if (candidate.getName().equals(name)
                        && candidate.getParameterTypes().length == args.length) {
                    m = candidate;
                    break;
                }
            }
            synchronized (MEMBERS) {
                MEMBERS.put(k, m);
            }
        }
        return m == MISSING ? null : ((java.lang.reflect.Method) m).invoke(target, args);
    }

    /** Read the field {@code name} declared on the class of {@code target} or a superclass. */
    private static Object read(Object target, String name) throws Exception {
        Class<?> cls = target.getClass();
        String k = cls.getName() + "." + name;
        Object f;
        synchronized (MEMBERS) {
            f = MEMBERS.get(k);
        }
        if (f == null) {
            f = MISSING;
            for (Class<?> c = cls; c != null && f == MISSING; c = c.getSuperclass()) {
                for (java.lang.reflect.Field candidate : c.getDeclaredFields()) {
                    if (candidate.getName().equals(name)) {
                        candidate.setAccessible(true);
                        f = candidate;
                        break;
                    }
                }
            }
            synchronized (MEMBERS) {
                MEMBERS.put(k, f);
            }
        }
        return f == MISSING ? null : ((java.lang.reflect.Field) f).get(target);
    }

    /**
     * Stamp delegate: forwards every callback to the app's delegate when there
     * is one, and to the platform default otherwise, then adds the stamp to the
     * node. A callback re-entered while it is being forwarded goes to the
     * platform default: an app delegate that wraps the delegate it found on the
     * view (as {@code ViewCompat} does) would otherwise call back into this one
     * forever.
     */
    static final class Delegate extends View.AccessibilityDelegate {
        private static final int SEND = 0;
        private static final int PERFORM = 1;
        private static final int SEND_UNCHECKED = 2;
        private static final int DISPATCH_POPULATE = 3;
        private static final int POPULATE = 4;
        private static final int INIT_EVENT = 5;
        private static final int INIT_NODE = 6;
        private static final int EXTRA_DATA = 7;
        private static final int REQUEST_SEND = 8;
        private static final int PROVIDER = 9;

        /** The app's delegate, or {@code null} when the app set none. */
        volatile View.AccessibilityDelegate app;
        /** Handler class names, {@code null} when no listener is set. */
        private volatile String click;
        private volatile String longClick;
        /** Callbacks currently being forwarded to {@link #app}, by index. */
        private final boolean[] busy = new boolean[10];

        Delegate(View.AccessibilityDelegate app) {
            this.app = app;
        }

        /** Set the stamp under {@code key}; return the previous value. */
        String put(String key, String cls) {
            String prev;
            if (KEY_CLICK.equals(key)) {
                prev = click;
                click = cls;
            } else {
                prev = longClick;
                longClick = cls;
            }
            return prev;
        }

        private View.AccessibilityDelegate enter(int which) {
            View.AccessibilityDelegate a = app;
            if (a == null || a == this || busy[which]) {
                return null;
            }
            busy[which] = true;
            return a;
        }

        @Override
        public void onInitializeAccessibilityNodeInfo(View host, AccessibilityNodeInfo info) {
            View.AccessibilityDelegate a = enter(INIT_NODE);
            if (a != null) {
                try {
                    a.onInitializeAccessibilityNodeInfo(host, info);
                } finally {
                    busy[INIT_NODE] = false;
                }
            } else {
                super.onInitializeAccessibilityNodeInfo(host, info);
            }
            try {
                Bundle extras = info.getExtras();
                if (click != null) {
                    extras.putString(KEY_CLICK, click);
                } else {
                    extras.remove(KEY_CLICK);
                }
                if (longClick != null) {
                    extras.putString(KEY_LONG_CLICK, longClick);
                } else {
                    extras.remove(KEY_LONG_CLICK);
                }
            } catch (Throwable ignored) {
                // The stamp is an observation; the node is already populated.
            }
        }

        @Override
        public void sendAccessibilityEvent(View host, int eventType) {
            View.AccessibilityDelegate a = enter(SEND);
            if (a == null) {
                super.sendAccessibilityEvent(host, eventType);
                return;
            }
            try {
                a.sendAccessibilityEvent(host, eventType);
            } finally {
                busy[SEND] = false;
            }
        }

        @Override
        public boolean performAccessibilityAction(View host, int action, Bundle args) {
            View.AccessibilityDelegate a = enter(PERFORM);
            if (a == null) {
                return super.performAccessibilityAction(host, action, args);
            }
            try {
                return a.performAccessibilityAction(host, action, args);
            } finally {
                busy[PERFORM] = false;
            }
        }

        @Override
        public void sendAccessibilityEventUnchecked(View host, AccessibilityEvent event) {
            View.AccessibilityDelegate a = enter(SEND_UNCHECKED);
            if (a == null) {
                super.sendAccessibilityEventUnchecked(host, event);
                return;
            }
            try {
                a.sendAccessibilityEventUnchecked(host, event);
            } finally {
                busy[SEND_UNCHECKED] = false;
            }
        }

        @Override
        public boolean dispatchPopulateAccessibilityEvent(View host, AccessibilityEvent event) {
            View.AccessibilityDelegate a = enter(DISPATCH_POPULATE);
            if (a == null) {
                return super.dispatchPopulateAccessibilityEvent(host, event);
            }
            try {
                return a.dispatchPopulateAccessibilityEvent(host, event);
            } finally {
                busy[DISPATCH_POPULATE] = false;
            }
        }

        @Override
        public void onPopulateAccessibilityEvent(View host, AccessibilityEvent event) {
            View.AccessibilityDelegate a = enter(POPULATE);
            if (a == null) {
                super.onPopulateAccessibilityEvent(host, event);
                return;
            }
            try {
                a.onPopulateAccessibilityEvent(host, event);
            } finally {
                busy[POPULATE] = false;
            }
        }

        @Override
        public void onInitializeAccessibilityEvent(View host, AccessibilityEvent event) {
            View.AccessibilityDelegate a = enter(INIT_EVENT);
            if (a == null) {
                super.onInitializeAccessibilityEvent(host, event);
                return;
            }
            try {
                a.onInitializeAccessibilityEvent(host, event);
            } finally {
                busy[INIT_EVENT] = false;
            }
        }

        @Override
        public void addExtraDataToAccessibilityNodeInfo(View host, AccessibilityNodeInfo info,
                String extraDataKey, Bundle arguments) {
            View.AccessibilityDelegate a = enter(EXTRA_DATA);
            if (a == null) {
                super.addExtraDataToAccessibilityNodeInfo(host, info, extraDataKey, arguments);
                return;
            }
            try {
                a.addExtraDataToAccessibilityNodeInfo(host, info, extraDataKey, arguments);
            } finally {
                busy[EXTRA_DATA] = false;
            }
        }

        @Override
        public boolean onRequestSendAccessibilityEvent(ViewGroup host, View child,
                AccessibilityEvent event) {
            View.AccessibilityDelegate a = enter(REQUEST_SEND);
            if (a == null) {
                return super.onRequestSendAccessibilityEvent(host, child, event);
            }
            try {
                return a.onRequestSendAccessibilityEvent(host, child, event);
            } finally {
                busy[REQUEST_SEND] = false;
            }
        }

        @Override
        public AccessibilityNodeProvider getAccessibilityNodeProvider(View host) {
            View.AccessibilityDelegate a = enter(PROVIDER);
            if (a == null) {
                return super.getAccessibilityNodeProvider(host);
            }
            try {
                return a.getAccessibilityNodeProvider(host);
            } finally {
                busy[PROVIDER] = false;
            }
        }
    }
}
