package br.unb.cic.rv.emitter;

import br.unb.cic.rv.descriptor.AdviceDescriptor;
import br.unb.cic.rv.descriptor.AspectDescriptor;
import br.unb.cic.rv.descriptor.MonitorCallDescriptor;
import br.unb.cic.rv.descriptor.ParameterDescriptor;
import br.unb.cic.rv.pointcut.CallPC;
import br.unb.cic.rv.pointcut.CombinedPC;
import br.unb.cic.rv.pointcut.PointcutExpression;
import br.unb.cic.rv.pointcut.PointcutExpressionParser;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Emits {@code mop/MonitorWrappers.java} — a Java source file containing one
 * static wrapper per advice whose hook would otherwise cause register aliasing
 * at injection time. The canonical trigger is {@code after() returning(R r)}
 * on a static factory like {@code Iterator.iterator()}: the weaver needs both
 * the return value and the original argument registers alive at once, and the
 * compiler may well have reused the arg register for the result.
 *
 * <p>Each wrapper:
 * <ol>
 *   <li>Calls the original static method with the same arguments.</li>
 *   <li>Invokes every {@code <RuntimeMonitor>.<Event>(...)} declared by the
 *       advice's {@code monitorCalls} list.</li>
 *   <li>Returns the original result.</li>
 * </ol>
 *
 * <p>At weave time, the {@code dex-mutator} rewrites the call-site's
 * {@code invoke-static} method reference from {@code ClassName.method(args)R}
 * to {@code mop.MonitorWrappers.<wrapperName>(args)R}. The original registers
 * and the {@code move-result*} are kept untouched — no spill needed.
 *
 * <p>Spec-set agnostic: emits wrappers for any {@code after-returning} advice
 * regardless of whether the underlying specification set is JCA or Generic.
 *
 * <p>Implementation note: the prototype's {@code WrapperGenerator} included an
 * android.jar-backed overload-resolution pass so that wrappers respected the
 * Android API's actual parameter types (not the host JDK's). That pass is
 * re-integrated by the {@code dex-mutator} in Group 5 via its
 * {@link br.unb.cic.rv.pointcut.AndroidClassIndex}; the version here uses the
 * advice parameter declarations as the source of truth, which matches how
 * rv-monitor emits the descriptor in both specification sets.
 */
public final class WrapperEmitter {

    public static final String WRAPPER_CLASS_NAME = "MonitorWrappers";
    public static final String WRAPPER_PACKAGE    = "mop";
    public static final String WRAPPER_CLASS_DESC = "Lmop/MonitorWrappers;";

    /** A wrapper entry: metadata the {@code dex-mutator} needs when rewriting call-sites. */
    public static final class WrapperEntry {
        public final String wrapperName;
        public final String originalClassFqn;
        public final String originalMethodName;
        public final List<String> originalParamFqn;
        public final String originalReturnFqn;

        public WrapperEntry(String wrapperName, String cls, String meth,
                            List<String> params, String ret) {
            this.wrapperName = wrapperName;
            this.originalClassFqn = cls;
            this.originalMethodName = meth;
            this.originalParamFqn = params;
            this.originalReturnFqn = ret;
        }
    }

    private WrapperEmitter() {}

    /**
     * Decide whether an advice should be routed through a wrapper.
     * Criteria: {@code after} position with a {@code returning(R r)} clause
     * (both the return object and the input args are needed by the monitor,
     * and the compiler may reuse the arg register for the result).
     */
    public static boolean shouldWrap(AdviceDescriptor a) {
        if (!"after".equals(a.getPosition())) return false;
        return a.getReturning() != null && !a.getReturning().isEmpty();
    }

    /**
     * Generate {@code mop/MonitorWrappers.java} under {@code outputDir} and
     * return the wrapper entries the {@code dex-mutator} needs.
     */
    public static List<WrapperEntry> generate(AspectDescriptor descriptor, Path outputDir)
            throws IOException {
        List<WrapperEntry> entries = new ArrayList<>();
        StringBuilder src = new StringBuilder();
        src.append("// Generated by rvsec-instrumentation-dexlib2 WrapperEmitter — DO NOT EDIT.\n");
        src.append("package ").append(WRAPPER_PACKAGE).append(";\n\n");

        Map<String, Integer> nameCounts = new LinkedHashMap<>();
        boolean bodyStarted = false;
        for (AdviceDescriptor advice : descriptor.getAdvices()) {
            if (!shouldWrap(advice)) continue;
            CallPC target = firstCallTarget(advice.getExpression());
            if (target == null) continue;
            if (target.isConstructor()) {
                // Constructors don't flow through wrappers — the weaver always
                // has access to the allocated instance as the invoke site's
                // first register.
                continue;
            }
            if (!bodyStarted) {
                src.append("public final class ").append(WRAPPER_CLASS_NAME).append(" {\n");
                src.append("    private ").append(WRAPPER_CLASS_NAME).append("() {}\n\n");
                bodyStarted = true;
            }
            WrapperEntry entry = buildEntry(target, nameCounts);
            entries.add(entry);
            appendWrapperMethod(src, advice, entry);
        }
        if (!bodyStarted) {
            // Emit an empty class so monitor-builder compiles uniformly
            // whether wrappers exist or not.
            src.append("public final class ").append(WRAPPER_CLASS_NAME).append(" {\n");
            src.append("    private ").append(WRAPPER_CLASS_NAME).append("() {}\n");
        }
        src.append("}\n");

        Path dir = outputDir.resolve(WRAPPER_PACKAGE);
        Files.createDirectories(dir);
        Files.writeString(dir.resolve(WRAPPER_CLASS_NAME + ".java"), src.toString());
        return entries;
    }

    // --- helpers -------------------------------------------------------------

    /**
     * Walks the pointcut AST and returns the first {@link CallPC} it finds.
     * The corpus uses one call(...) per advice in practice; the walk flattens
     * the AST to pick it up regardless of whether it's nested in {@code &&} /
     * {@code ||} subtrees.
     */
    private static CallPC firstCallTarget(String expression) {
        if (expression == null || expression.isBlank()) return null;
        try {
            PointcutExpression pe = PointcutExpressionParser.parse(expression);
            return findFirstCall(pe);
        } catch (RuntimeException ex) {
            return null;
        }
    }

    private static CallPC findFirstCall(PointcutExpression pe) {
        if (pe instanceof CallPC cpc) return cpc;
        if (pe instanceof CombinedPC c) {
            CallPC left = findFirstCall(c.left());
            if (left != null) return left;
            return findFirstCall(c.right());
        }
        return null;
    }

    private static WrapperEntry buildEntry(CallPC target, Map<String, Integer> nameCounts) {
        String cls = target.declaringType();
        String meth = target.methodName();
        String baseName = cls.replace('.', '_') + "_" + meth;
        int count = nameCounts.getOrDefault(baseName, 0);
        nameCounts.put(baseName, count + 1);
        String wrapperName = count == 0 ? baseName : baseName + "_" + count;

        List<String> params = new ArrayList<>(target.paramTypes());
        String ret = target.returnType();
        return new WrapperEntry(wrapperName, cls, meth, params, ret);
    }

    private static void appendWrapperMethod(StringBuilder src, AdviceDescriptor advice,
                                             WrapperEntry entry) {
        String ret = entry.originalReturnFqn;
        src.append("    public static ").append(ret).append(' ').append(entry.wrapperName)
                .append('(');
        List<String> paramNames = new ArrayList<>();
        for (int i = 0; i < entry.originalParamFqn.size(); i++) {
            if (i > 0) src.append(", ");
            String p = entry.originalParamFqn.get(i);
            String name = "p" + i;
            paramNames.add(name);
            src.append(p).append(' ').append(name);
        }
        src.append(") {\n");
        src.append("        ").append(ret).append(" result = ").append(entry.originalClassFqn)
                .append('.').append(entry.originalMethodName).append('(')
                .append(String.join(", ", paramNames)).append(");\n");

        for (MonitorCallDescriptor mc : advice.getMonitorCalls()) {
            src.append("        ").append(mc.getMethod()).append('(');
            src.append(buildMonitorArgs(advice, mc, paramNames));
            src.append(");\n");
        }
        src.append("        return result;\n");
        src.append("    }\n\n");
    }

    private static String buildMonitorArgs(AdviceDescriptor advice, MonitorCallDescriptor mc,
                                            List<String> wrapperParamNames) {
        Collection<String> args = new ArrayList<>();
        Map<String, String> byName = new LinkedHashMap<>();
        for (int i = 0; i < advice.getParameters().size(); i++) {
            ParameterDescriptor pd = advice.getParameters().get(i);
            String local = i < wrapperParamNames.size()
                    ? wrapperParamNames.get(i)
                    : pd.getName();
            byName.put(pd.getName(), local);
        }
        if (advice.getReturning() != null) {
            for (ParameterDescriptor pd : advice.getReturning()) {
                byName.put(pd.getName(), "result");
            }
        }
        for (String argName : mc.getArgs()) {
            args.add(byName.getOrDefault(argName, argName));
        }
        return String.join(", ", args);
    }
}
