package br.unb.cic.mop;

/**
 * The properties that we are interested in.
 *
 */
public enum Property {
	GENERATED_KEY,
    DIGESTED,
    ENCRYPTED,
    GENERATED_MAC,
    GENERATED_PRIVATE_KEY,
    GENERATED_PUBLIC_KEY,
    GENERATE_SSL_CONTEXT,
    GENERATE_SSL_ENGINE,
    GENERATED_KEY_MANAGERS,
    GENERATED_KEY_PAIR,
    GENERATED_TRUST_MANAGER,
    GENERATED_TRUST_MANAGERS,
    GENERATED_KEY_STORE,
    PREPARED_DH,
    PREPARED_GCM,
    PREPARED_HMAC,
    PREPARED_PBE,
    PREPARED_IV,
    RANDOMIZED,
    SIGNED,
    SPECCED_KEY,
    VERIFIED,
    WRAPPED_KEY
}
