
EXTENSION_AJ = ".aj"
EXTENSION_APK = ".apk"
EXTENSION_CSV = ".csv"
EXTENSION_DEX = ".dex"
EXTENSION_JAVA = ".java"
EXTENSION_JAR = ".jar"
EXTENSION_MOP = ".mop"
EXTENSION_RVM = ".rvm"

EXTENSION_LOGCAT = ".logcat"
EXTENSION_METHODS = ".methods"
EXTENSION_TRACE = ".trace"
