#!/usr/bin/env python3
"""
Custom Analyzer for RV-Android Test Results
==========================================

This module provides a comprehensive solution for analyzing test results
from CSV files generated by the RV-Android test framework. It focuses
particularly on Monitoring-Oriented Programming (MOP) metrics, which track
violations of monitored specifications during application testing.

Key Features:
------------
1. Directly processes CSV files without requiring prior analysis
2. Generates detailed JSON and Excel reports with comprehensive metrics
3. Focuses on monitored operations metrics (MOP) for specification violations
4. Creates visualizations to easily identify patterns and issues
5. Provides detailed summaries of test execution and error detection

This analyzer is specifically designed to work with the updated test framework
that incorporates Monitored Operations (MOP) metrics, replacing the previous
security-focused metrics with a more comprehensive approach that handles both
security specifications and general programming specifications.
"""

import csv
import json
import os
import sys
from datetime import datetime
from typing import Dict, List, Any

import matplotlib.pyplot as plt
import pandas as pd


def read_csv_file(filepath: str) -> List[Dict[str, Any]]:
    """
    Read a CSV file and return a list of dictionaries.
    
    Args:
        filepath: Path to the CSV file
        
    Returns:
        List of dictionaries where each dictionary represents a row in the CSV file
        
    This function handles cases where the file doesn't exist or can't be properly
    read, returning an empty list in those cases with appropriate warning messages.
    """
    if not os.path.exists(filepath):
        print(f"Warning: File not found: {filepath}")
        return []

    results = []
    try:
        with open(filepath, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                results.append(row)
        return results
    except Exception as e:
        print(f"Error reading {filepath}: {str(e)}")
        return []


def analyze_results(directory: str, output_dir: str = "analysis_results") -> bool:
    """
    Analyze test results directly from CSV files.
    
    This function is the main entry point for analyzing test results. It processes:
    - coverage_data.csv: Contains information about method and activity coverage
    - error_data.csv: Contains information about crashed and exceptions
    - mop_error_data.csv: Contains information about monitored operations errors
    - monitored_operations.csv: Contains details about monitored specifications
    
    The function combines these data sources to create a comprehensive analysis,
    with special focus on Monitoring-Oriented Programming (MOP) metrics that track
    violations of both security specifications and general programming specifications.
    
    Args:
        directory: Directory containing CSV files with test results
        output_dir: Directory to save analysis results and visualizations
        
    Returns:
        True if analysis was successful, False otherwise
    """
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    # Check if directory exists
    if not os.path.exists(directory):
        print(f"Error: Directory not found: {directory}")
        return False

    # Read CSV files
    coverage_file = os.path.join(directory, "coverage_data.csv")
    error_file = os.path.join(directory, "error_data.csv")
    mop_error_file = os.path.join(directory, "mop_error_data.csv")
    monitored_ops_file = os.path.join(directory, "monitored_operations.csv")

    coverage_data = read_csv_file(coverage_file)
    error_data = read_csv_file(error_file)
    mop_error_data = read_csv_file(mop_error_file)
    monitored_ops_data = read_csv_file(monitored_ops_file)

    # Check if data exists
    if not coverage_data:
        print("No coverage data found")
        return False

    # Create analysis results
    analysis_results = {
        "timestamp": datetime.now().isoformat(),
        "total_results": len(coverage_data),
        "source_directory": directory,
        "coverage_data": coverage_data,
        "error_data": error_data,
        "mop_error_data": mop_error_data,
        "monitored_operations_data": monitored_ops_data
    }

    # Extract configurations
    configs = {}
    for row in coverage_data:
        config_id = row.get("test_id")
        if config_id:
            # Split ID to get tool, model, etc.
            parts = config_id.split("_")
            tool = parts[0] if len(parts) > 0 else "unknown"

            # Extract metrics
            metrics = {
                "method_coverage": float(row.get("method_coverage", 0)),
                "activity_coverage": float(row.get("activity_coverage", 0)),
                "mop_method_coverage": float(row.get("mop_method_coverage", 0)),
                "execution_time": float(row.get("execution_time", 0)),
                "status": row.get("status", "unknown")
            }

            # Find corresponding MOP data
            for mop_row in mop_error_data:
                if mop_row.get("test_id") == config_id:
                    metrics["mop_error_count"] = int(mop_row.get("mop_error_count", 0))
                    metrics["mop_unique_errors"] = int(mop_row.get("mop_unique_errors", 0))
                    metrics["mop_error_rate"] = float(mop_row.get("mop_error_rate", 0))
                    metrics["monitored_operations_ratio"] = float(mop_row.get("monitored_operations_ratio", 0))
                    break

            # Find corresponding monitored ops data
            for ops_row in monitored_ops_data:
                if ops_row.get("test_id") == config_id:
                    metrics["monitored_operations_count"] = int(ops_row.get("monitored_operations_count", 0))
                    metrics["monitored_operations_triggered"] = int(ops_row.get("monitored_operations_triggered", 0))
                    metrics["triggered_specifications"] = ops_row.get("triggered_specifications", "[]")
                    break

            # Store configuration
            configs[config_id] = {
                "tool": tool,
                "metrics": metrics,
                "app": row.get("app", "unknown"),
                "llm_model": row.get("llm_model", "unknown"),
                "strategy": row.get("strategy", "unknown")
            }

    # Add configurations to results
    analysis_results["configurations"] = configs

    # Calculate averages
    avg_method_coverage = sum(float(row.get("method_coverage", 0)) for row in coverage_data) / len(
        coverage_data) if coverage_data else 0
    avg_activity_coverage = sum(float(row.get("activity_coverage", 0)) for row in coverage_data) / len(
        coverage_data) if coverage_data else 0
    avg_mop_method_coverage = sum(float(row.get("mop_method_coverage", 0)) for row in coverage_data) / len(
        coverage_data) if coverage_data else 0
    avg_execution_time = sum(float(row.get("execution_time", 0)) for row in coverage_data) / len(
        coverage_data) if coverage_data else 0

    # Add average metrics
    analysis_results["avg_metrics"] = {
        "avg_method_coverage": avg_method_coverage,
        "avg_activity_coverage": avg_activity_coverage,
        "avg_mop_method_coverage": avg_mop_method_coverage,
        "avg_execution_time": avg_execution_time
    }

    # Add MOP metrics
    if mop_error_data:
        avg_mop_error_count = sum(int(row.get("mop_error_count", 0)) for row in mop_error_data) / len(mop_error_data)
        avg_mop_unique_errors = sum(int(row.get("mop_unique_errors", 0)) for row in mop_error_data) / len(
            mop_error_data)
        avg_mop_error_rate = sum(float(row.get("mop_error_rate", 0)) for row in mop_error_data if
                                 float(row.get("mop_error_rate", 0)) > 0) / sum(
            1 for row in mop_error_data if float(row.get("mop_error_rate", 0)) > 0) if sum(
            1 for row in mop_error_data if float(row.get("mop_error_rate", 0)) > 0) > 0 else 0

        analysis_results["avg_metrics"].update({
            "avg_mop_error_count": avg_mop_error_count,
            "avg_mop_unique_errors": avg_mop_unique_errors,
            "avg_mop_error_rate": avg_mop_error_rate
        })

    # Save analysis results
    output_file = os.path.join(output_dir, "analysis_results.json")
    with open(output_file, 'w') as f:
        json.dump(analysis_results, f, indent=2)
    print(f"Analysis results saved to: {output_file}")

    # Generate visualizations
    generate_visualizations(analysis_results, output_dir)

    # Generate Excel report
    generate_excel_report(analysis_results, output_dir)

    return True


def generate_visualizations(analysis_results: Dict[str, Any], output_dir: str) -> None:
    """
    Generate visualizations from analysis results.
    
    This function creates a variety of visualizations that help analyze test results:
    - Coverage charts showing method, activity, and MOP-specific method coverage
    - MOP error charts showing the count and variety of specification violations
    - Monitored operations ratio charts showing how thoroughly monitored code was tested
    
    These visualizations are designed to highlight both general test coverage and
    specifically how well the testing approached monitored operations specifications,
    including both security specifications and general programming specifications.
    
    Args:
        analysis_results: Dictionary containing processed analysis results
        output_dir: Directory to save visualization files
    """
    # Create coverage chart
    if "coverage_data" in analysis_results and analysis_results["coverage_data"]:
        # Convert to DataFrame
        df = pd.DataFrame(analysis_results["coverage_data"])

        # Convert string columns to numeric
        for col in ["method_coverage", "activity_coverage", "mop_method_coverage"]:
            df[col] = pd.to_numeric(df[col], errors='coerce')

        # Create figure
        plt.figure(figsize=(10, 6))

        # Plot coverage
        plt.bar(df.index, df["method_coverage"], label="Method Coverage")
        plt.bar(df.index, df["activity_coverage"], label="Activity Coverage", alpha=0.7)
        plt.bar(df.index, df["mop_method_coverage"], label="MOP Method Coverage", alpha=0.5)

        # Add labels
        plt.xlabel("Test Case")
        plt.ylabel("Coverage (%)")
        plt.title("Coverage Metrics")
        plt.legend()

        # Save chart
        plt.savefig(os.path.join(output_dir, "coverage_chart.png"), dpi=100)
        plt.close()

    # Create MOP error chart
    if "mop_error_data" in analysis_results and analysis_results["mop_error_data"]:
        # Convert to DataFrame
        df = pd.DataFrame(analysis_results["mop_error_data"])

        # Convert string columns to numeric
        for col in ["mop_error_count", "mop_unique_errors", "mop_error_rate", "monitored_operations_ratio"]:
            df[col] = pd.to_numeric(df[col], errors='coerce')

        # Create figure
        plt.figure(figsize=(10, 6))

        # Plot MOP errors
        plt.bar(df.index, df["mop_error_count"], label="MOP Error Count")
        plt.bar(df.index, df["mop_unique_errors"], label="Unique MOP Errors", alpha=0.7)

        # Add labels
        plt.xlabel("Test Case")
        plt.ylabel("Count")
        plt.title("MOP Error Metrics")
        plt.legend()

        # Save chart
        plt.savefig(os.path.join(output_dir, "mop_error_chart.png"), dpi=100)
        plt.close()

        # Create monitored operations ratio chart
        plt.figure(figsize=(10, 6))
        plt.bar(df.index, df["monitored_operations_ratio"], color="teal")
        plt.xlabel("Test Case")
        plt.ylabel("Ratio (%)")
        plt.title("Monitored Operations Ratio")
        plt.savefig(os.path.join(output_dir, "monitored_ops_ratio_chart.png"), dpi=100)
        plt.close()


def generate_excel_report(analysis_results: Dict[str, Any], output_dir: str) -> None:
    """
    Generate Excel report from analysis results.
    
    This function creates a comprehensive Excel report with multiple sheets:
    - Coverage Data: Details on method and activity coverage for each test
    - MOP Error Data: Information about monitored operations specification violations
    - Monitored Operations: Details about which specifications were triggered
    - Summary: Overview of key metrics across all tests
    
    The Excel report is designed to make MOP metrics highly visible and accessible,
    ensuring that violations of both security specifications and general programming
    specifications are easy to identify and analyze.
    
    Args:
        analysis_results: Dictionary containing processed analysis results
        output_dir: Directory to save the Excel report
    """
    # Create Excel file
    excel_file = os.path.join(output_dir, "analysis_report.xlsx")

    # Create Excel writer
    with pd.ExcelWriter(excel_file, engine='openpyxl') as writer:
        # Write coverage data
        if "coverage_data" in analysis_results and analysis_results["coverage_data"]:
            df = pd.DataFrame(analysis_results["coverage_data"])
            df.to_excel(writer, sheet_name="Coverage Data", index=False)

        # Write MOP error data
        if "mop_error_data" in analysis_results and analysis_results["mop_error_data"]:
            df = pd.DataFrame(analysis_results["mop_error_data"])
            df.to_excel(writer, sheet_name="MOP Error Data", index=False)

        # Write monitored operations data
        if "monitored_operations_data" in analysis_results and analysis_results["monitored_operations_data"]:
            df = pd.DataFrame(analysis_results["monitored_operations_data"])
            df.to_excel(writer, sheet_name="Monitored Operations", index=False)

        # Write summary
        summary_data = {
            "Metric": [
                "Total Test Cases",
                "Average Method Coverage",
                "Average Activity Coverage",
                "Average MOP Method Coverage",
                "Average Execution Time"
            ],
            "Value": [
                analysis_results.get("total_results", 0),
                analysis_results.get("avg_metrics", {}).get("avg_method_coverage", 0),
                analysis_results.get("avg_metrics", {}).get("avg_activity_coverage", 0),
                analysis_results.get("avg_metrics", {}).get("avg_mop_method_coverage", 0),
                analysis_results.get("avg_metrics", {}).get("avg_execution_time", 0)
            ]
        }

        # Add MOP metrics if available
        if "avg_metrics" in analysis_results and "avg_mop_error_count" in analysis_results["avg_metrics"]:
            summary_data["Metric"].extend([
                "Average MOP Error Count",
                "Average Unique MOP Errors",
                "Average MOP Error Rate"
            ])
            summary_data["Value"].extend([
                analysis_results["avg_metrics"].get("avg_mop_error_count", 0),
                analysis_results["avg_metrics"].get("avg_mop_unique_errors", 0),
                analysis_results["avg_metrics"].get("avg_mop_error_rate", 0)
            ])

        # Create DataFrame and write to Excel
        summary_df = pd.DataFrame(summary_data)
        summary_df.to_excel(writer, sheet_name="Summary", index=False)

    print(f"Excel report saved to: {excel_file}")


if __name__ == "__main__":
    # Check arguments
    if len(sys.argv) < 2:
        print("Usage: python custom_analyzer.py <results_directory> [output_directory]")
        sys.exit(1)

    # Get directory from command line
    directory = sys.argv[1]

    # Get output directory if provided
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "analysis_results"

    # Analyze results
    analyze_results(directory, output_dir)
