blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/PAMunb/rvsec/tree/modules/rv-android/docs
    about: Check the project documentation before opening an issue.
