package br.unb.cic.rv.builder;

import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class CoverageSourceEmitterTest {

    @Test
    void emittedSourceUsesConcurrentHashMapKeySet() {
        String src = CoverageSourceEmitter.sourceText();
        assertTrue(src.contains("ConcurrentHashMap.newKeySet"),
                "INV-INS-23: backing store must be ConcurrentHashMap.newKeySet()");
        assertFalse(src.contains("HashSet"),
                "INV-INS-23: plain HashSet must not appear in the generated source");
    }

    @Test
    void emittedSourceDeclaresPublicApi() {
        String src = CoverageSourceEmitter.sourceText();
        assertTrue(src.contains("public static void log(String signature)"));
        assertTrue(src.contains("public static int size()"));
        assertTrue(src.contains("public static Iterable<String> seen()"));
    }

    @Test
    void emittedSourceUsesCorrectLogcatTag() {
        String src = CoverageSourceEmitter.sourceText();
        assertTrue(src.contains("\"RVSEC-COV\""),
                "the logcat TAG must be RVSEC-COV to match the parser contract");
    }

    @Test
    void emitToDiskWritesFileUnderMopPackage(@org.junit.jupiter.api.io.TempDir Path tmp)
            throws Exception {
        Path file = CoverageSourceEmitter.emit(tmp);
        assertTrue(Files.isRegularFile(file));
        assertEquals("Coverage.java", file.getFileName().toString());
        assertEquals("mop", file.getParent().getFileName().toString());
        String body = Files.readString(file);
        assertTrue(body.startsWith("// Generated by rvsec-instrumentation-dexlib2"));
    }
}
