"""
ReactEngine for RVAgent - ReAct pattern implementation.

EXACT implementation of the plan with single LLM call and process isolation.
ReAct (Reasoning + Acting) pattern for autonomous client decisions.
"""
import time
from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass

from rv_android_core.util.logging.manager import LoggingManager
from rv_android_core.util.error.error_handler import ErrorHandler

from ..constants import RVAgentConstants
from ..memory.short_term import ShortTermMemory
from ..memory.long_term import LongTermMemory
from ..memory.ui_coverage import UICoverageTracker
from ..llm.langchain_service import LangChainService


@dataclass
class ReactAction:
    """
    Represents an action generated by the ReAct engine.

    Actions generated by LLM+Tools approach may be already executed by tools.
    """
    reasoning: str
    action_type: str
    element_id: str = ""
    coordinates: List[int] = None
    input_text: str = ""
    confidence: float = 0.0
    already_executed: bool = False  # True if LLM tool already executed this action

    def __post_init__(self):
        if self.coordinates is None:
            self.coordinates = []

    def to_device_action(self) -> Dict[str, Any]:
        """Convert to DeviceInterface action format."""
        return {
            'action_type': self.action_type,
            'element_id': self.element_id,
            'coordinates': self.coordinates,
            'input_text': self.input_text,
            'confidence': self.confidence
        }


class ReactEngine:
    """
    ReAct (Reasoning + Acting) Engine for RVAgent client.

    SUBPROCESS ISOLATED PROCESS:
    - LoggingManager.get_instance() with own subprocess instance
    - ErrorHandler.get_instance() with own subprocess instance
    - Integrated memory components (ShortTerm, LongTerm, UICoverage)
    - Single LLM call pattern (Phase 0 optimization)

    Target: br.unb.cic.cryptoapp - Autonomous testing decisions
    """

    def __init__(self, short_term_memory: ShortTermMemory,
                 long_term_memory: LongTermMemory,
                 ui_coverage_tracker: UICoverageTracker,
                 llm_service: LangChainService):
        """Initialize ReactEngine with process isolation support."""

        # Process isolation - LoggingManager with own instance
        logging_manager = LoggingManager.get_instance()
        self.logger = logging_manager.get_logger(
            "rv_agent.core.react_engine",
            {"component": "ReactEngine"}
        )

        # ErrorHandler decorators available in subprocess
        self.error_handler = ErrorHandler.get_instance()

        # Memory integration
        self.short_term_memory = short_term_memory
        self.long_term_memory = long_term_memory
        self.ui_coverage_tracker = ui_coverage_tracker

        # LLM integration (MANDATORY)
        self.llm_service = llm_service
        self.logger.info("[RVAGENT_DEBUG] ReactEngine initialized with LLM service")

        # ReAct state
        self.current_objective = "explore_application"
        self.iteration_count = 0

        self.logger.info("[RVAGENT_DEBUG] ReactEngine initialized with memory integration")

    def decide_next_action(self, ui_state: Dict[str, Any], screenshot_path: Optional[str] = None) -> List[ReactAction]:
        """
        Main ReAct decision method - single LLM call pattern.

        Combines: Observation → Reasoning → Multiple Actions (1-3) in a single call.
        Phase 0 optimization: reduces latency and token usage.

        Args:
            ui_state: Current UI state from DeviceInterface

        Returns:
            List of ReactActions with reasoning and action specifications
        """
        try:
            self.iteration_count += 1
            state_hash = ui_state.get('hash_screen', 'unknown')
            activity = ui_state.get('activity', 'unknown')

            self.logger.debug(f"[RVAGENT_DEBUG] Starting ReAct iteration #{self.iteration_count}")

            # Phase 1: Observation (gather context)
            observation_context = self._gather_observation_context(ui_state)

            # Phase 2: Reasoning (LLM ReAct decision) with screenshot
            actions = self._perform_llm_reasoning(observation_context, ui_state, screenshot_path)

            if not actions:
                self.logger.warning("[RVAGENT_DEBUG] No actions generated by LLM")
                return []

            # Update memories with actions
            self._update_memories(ui_state, actions)

            self.logger.info(f"[RVAGENT_DEBUG] ReAct decision complete: {len(actions)} actions generated")
            for i, action in enumerate(actions):
                self.logger.info(f"[RVAGENT_DEBUG]   Action {i+1}: {action.action_type} "
                               f"({action.element_id}) - Confidence: {action.confidence:.2f}")

            return actions

        except Exception as e:
            self.logger.error(f"[RVAGENT_DEBUG] ReAct decision failed: {e}")
            return []

    def _gather_observation_context(self, ui_state: Dict[str, Any]) -> Dict[str, Any]:
        """
        Gather comprehensive context for ReAct reasoning.

        Combines:
        - Current UI state
        - Short term memory (recent actions)
        - Long term memory (state history)
        - UI coverage data (testing completeness)
        """
        try:
            state_hash = ui_state.get('hash_screen', 'unknown')

            # Get memory contexts
            short_term_context = self.short_term_memory.get_current_screen_context()
            long_term_guidance = self.long_term_memory.get_state_guidance(state_hash)
            coverage_stats = self.ui_coverage_tracker.get_screen_coverage_stats(state_hash)

            # Get exploration suggestions
            exploration_suggestions = self.ui_coverage_tracker.get_exploration_suggestions(state_hash, limit=3)

            context = {
                # UI State
                'current_activity': ui_state.get('activity', 'unknown'),
                'element_count': ui_state.get('element_count', 0),
                'clickable_elements': ui_state.get('clickable_elements', []),
                'formatted_elements': ui_state.get('formatted_elements', ''),

                # Memory context
                'short_term': short_term_context,
                'long_term': long_term_guidance,

                # Coverage context
                'coverage_percentage': coverage_stats.coverage_percentage,
                'tested_elements': coverage_stats.tested_elements,
                'untested_elements': coverage_stats.untested_elements,
                'exploration_suggestions': exploration_suggestions,

                # Session context
                'iteration_count': self.iteration_count,
                'current_objective': self.current_objective
            }

            self.logger.debug(f"[RVAGENT_DEBUG] Observation context gathered: "
                            f"{context['element_count']} elements, "
                            f"{context['coverage_percentage']:.1f}% coverage")

            return context

        except Exception as e:
            self.logger.error(f"[RVAGENT_DEBUG] Observation context failed: {e}")
            return {"error": str(e)}

    def _perform_llm_reasoning(self, context: Dict[str, Any], ui_state: Dict[str, Any], screenshot_path: Optional[str] = None) -> List[ReactAction]:
        """
        Perform ReAct reasoning using LangChain tool-calling agent.

        NEW APPROACH: LangChain AgentExecutor handles tool calling automatically.
        Tools are executed directly by the agent, not by ReactEngine.
        """
        try:
            self.logger.debug("[RVAGENT_DEBUG] Starting LangChain tool-calling ReAct reasoning...")

            # Prepare memory context
            memory_context = self.short_term_memory.format_for_template()

            # Prepare coverage stats
            state_hash = ui_state.get('hash_screen', 'unknown')
            coverage_stats = self.ui_coverage_tracker.get_screen_coverage_stats(state_hash)
            coverage_dict = {
                'tested_elements': coverage_stats.tested_elements,
                'untested_elements': coverage_stats.untested_elements,
                'coverage_percentage': coverage_stats.coverage_percentage
            }

            # Get exploration suggestions
            exploration_suggestions = self.ui_coverage_tracker.get_exploration_suggestions(state_hash)

            # Call LangChain service with tool-calling
            llm_response = self.llm_service.generate_react_decision(
                ui_state=ui_state,
                memory_context=memory_context,
                coverage_stats=coverage_dict,
                exploration_suggestions=exploration_suggestions,
                screenshot_path=screenshot_path
            )

            if not llm_response:
                self.logger.error("[RVAGENT_DEBUG] LangChain tool-calling failed")
                return []

            # Extract actions from tool calls (already executed)
            actions_data = llm_response.get('actions', [])
            if not actions_data:
                self.logger.warning("[RVAGENT_DEBUG] No tool calls executed by agent")
                return []

            # Convert tool calls to ReactActions (for compatibility)
            actions = []
            for i, action_data in enumerate(actions_data):
                action = ReactAction(
                    reasoning=action_data.get('reasoning', f'Tool call {i+1}'),
                    action_type=action_data.get('action_type', 'wait'),
                    element_id=action_data.get('element_id', ''),
                    coordinates=action_data.get('coordinates', []),
                    input_text=action_data.get('input_text', ''),
                    confidence=action_data.get('confidence', 0.8)  # Tool-calling has higher confidence
                )

                # Mark as already executed (tools already ran)
                action.already_executed = action_data.get('success', False)
                actions.append(action)

            self.logger.debug(f"[RVAGENT_DEBUG] Tool-calling complete: {len(actions)} tools executed")
            return actions

        except Exception as e:
            self.logger.error(f"[RVAGENT_DEBUG] LangChain tool-calling failed: {e}")
            return []

    def _select_action(self, reasoning: Dict[str, Any], ui_state: Dict[str, Any]) -> ReactAction:
        """
        Select concrete action based on reasoning results.

        Converts abstract reasoning into specific DeviceInterface action.
        """
        try:
            strategy = reasoning.get('exploration_strategy', 'balanced_exploration')
            confidence = reasoning.get('confidence_level', 0.5)

            clickable_elements = ui_state.get('clickable_elements', [])
            state_hash = ui_state.get('hash_screen', 'unknown')

            if not clickable_elements:
                return ReactAction(
                    reasoning="No clickable elements available",
                    action_type="wait",
                    confidence=0.1
                )

            # Select element based on strategy
            selected_element = None

            if strategy == "prioritize_untested_elements":
                # Find first untested element
                for element in clickable_elements:
                    element_id = self._extract_element_id(element)
                    if self.ui_coverage_tracker.is_element_untested(element_id):
                        selected_element = element
                        break

            elif strategy == "try_different_elements":
                # Find least tested elements
                sorted_elements = []
                for element in clickable_elements:
                    element_id = self._extract_element_id(element)
                    test_count = self.ui_coverage_tracker.get_element_test_count(element_id)
                    sorted_elements.append((element, test_count))

                sorted_elements.sort(key=lambda x: x[1])  # Sort by test count
                if sorted_elements:
                    selected_element = sorted_elements[0][0]

            # Fallback to first available element
            if not selected_element:
                selected_element = clickable_elements[0]

            # Extract action details
            element_id = self._extract_element_id(selected_element)
            # Try different coordinate sources
            coordinates = (selected_element.get('coordinates') or
                         selected_element.get('center') or
                         [])

            action = ReactAction(
                reasoning=reasoning.get('situation_analysis', 'Element exploration'),
                action_type="click",
                element_id=element_id,
                coordinates=coordinates,
                confidence=confidence
            )

            self.logger.debug(f"[RVAGENT_DEBUG] Action selected: {element_id} at {coordinates}")

            return action

        except Exception as e:
            self.logger.error(f"[RVAGENT_DEBUG] Action selection failed: {e}")
            return ReactAction(
                reasoning=f"Action selection error: {e}",
                action_type="wait",
                confidence=0.1
            )

    def _extract_element_id(self, element: Dict[str, Any]) -> str:
        """Extract consistent element ID from element data."""
        # Try different ID sources in order of preference
        element_id = (element.get('element_id') or
                     element.get('resource_id') or
                     element.get('description') or  # Use full description for better tracking
                     element.get('text') or
                     element.get('content_desc') or
                     f"element_{hash(str(element))}")

        return str(element_id)

    def _update_memories(self, ui_state: Dict[str, Any], actions: List[ReactAction]) -> None:
        """Update memory components with current decisions."""
        try:
            state_hash = ui_state.get('hash_screen', 'unknown')
            activity = ui_state.get('activity', 'unknown')

            # Update long term memory
            self.long_term_memory.record_state(
                state_hash=state_hash,
                activity=activity,
                interactive_elements_count=ui_state.get('element_count', 0)
            )

            # Update short term memory with planned actions
            actions_list = [action.to_device_action() for action in actions]
            # Combine reasoning from all actions
            combined_reasoning = '; '.join([action.reasoning for action in actions])
            self.short_term_memory.record_iteration(
                state=ui_state,
                actions=actions_list,
                llm_reasoning=combined_reasoning
            )

            self.logger.debug(f"[RVAGENT_DEBUG] Memory updated with {len(actions)} ReAct decisions")

        except Exception as e:
            self.logger.error(f"[RVAGENT_DEBUG] Memory update failed: {e}")

    def record_action_result(self, action: ReactAction, success: bool,
                           result_state: Optional[Dict[str, Any]] = None) -> None:
        """
        Record action execution result for learning.

        Args:
            action: The action that was executed
            success: Whether action was successful
            result_state: Resulting UI state (if available)
        """
        try:
            # Record in UI coverage tracker
            self.ui_coverage_tracker.record_interaction(
                element_id=action.element_id,
                action_type=action.action_type,
                success=success
            )

            # Record execution results in short term memory
            execution_results = [{
                'action_type': action.action_type,
                'element_id': action.element_id,
                'success': success,
                'timestamp': time.time()
            }]

            self.short_term_memory.record_execution_results(execution_results)

            # Record in long term memory if state transition occurred
            if result_state and success:
                result_hash = result_state.get('hash_screen', 'unknown')
                # Note: Would need current_state_hash to record transition
                # For now, just record the action execution

            success_text = "SUCCESS" if success else "FAILED"
            self.logger.debug(f"[RVAGENT_DEBUG] Action result recorded: {action.action_type} "
                            f"({action.element_id}) - {success_text}")

        except Exception as e:
            self.logger.error(f"[RVAGENT_DEBUG] Action result recording failed: {e}")

    def get_decision_statistics(self) -> Dict[str, Any]:
        """Get ReactEngine decision statistics."""
        try:
            short_term_stats = self.short_term_memory.get_statistics()
            long_term_stats = self.long_term_memory.get_statistics()
            coverage_stats = self.ui_coverage_tracker.get_overall_statistics()

            return {
                "iteration_count": self.iteration_count,
                "current_objective": self.current_objective,
                "short_term_memory": short_term_stats,
                "long_term_memory": long_term_stats,
                "ui_coverage": coverage_stats
            }

        except Exception as e:
            self.logger.error(f"[RVAGENT_DEBUG] Statistics calculation failed: {e}")
            return {"error": str(e)}

    def set_objective(self, objective: str) -> None:
        """Set current testing objective."""
        self.logger.info(f"[RVAGENT_DEBUG] Objective changed: {self.current_objective} → {objective}")
        self.current_objective = objective

    def reset_engine(self) -> None:
        """Reset ReactEngine state (for testing or new session)."""
        self.logger.info("[RVAGENT_DEBUG] Resetting ReactEngine state...")

        self.iteration_count = 0
        self.current_objective = "explore_application"

        self.logger.info("[RVAGENT_DEBUG] ReactEngine reset complete")