// Generated by rvsec-instrumentation-dexlib2 WrapperEmitter — DO NOT EDIT.
package mop;

import javax.crypto.CipherInputStream;
import java.io.InputStream;
import javax.crypto.Cipher;
import br.unb.cic.mop.eh.*;
import br.unb.cic.mop.ExecutionContext;
import br.unb.cic.mop.Property;
import javax.crypto.CipherOutputStream;
import java.io.OutputStream;
import java.security.Provider;
import java.security.Key;
import java.security.SecureRandom;
import java.security.spec.AlgorithmParameterSpec;
import java.nio.ByteBuffer;
import static br.unb.cic.mop.jca.util.AndroidCipherTransformationUtil.*;
import javax.crypto.spec.DHGenParameterSpec;
import javax.crypto.spec.GCMParameterSpec;
import javax.xml.crypto.dsig.spec.HMACParameterSpec;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.ManagerFactoryParameters;
import javax.net.ssl.KeyManager;
import java.security.KeyStore;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.KeyStore.ProtectionParameter;
import java.security.KeyStore.Entry;
import javax.crypto.Mac;
import java.security.MessageDigest;
import java.util.List;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.PBEParameterSpec;
import java.util.stream.IntStream;
import javax.crypto.spec.SecretKeySpec;
import java.security.Signature;
import java.security.cert.Certificate;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;
import javax.net.ssl.TrustManager;
import javax.net.ssl.TrustManagerFactory;
import java.util.concurrent.*;
import java.util.concurrent.locks.*;
import java.util.*;
import java.lang.ref.*;

public final class MonitorWrappers {
    private MonitorWrappers() {}

    public static int javax_crypto_CipherInputStream_read(javax.crypto.CipherInputStream recv) throws Exception {
        int result = recv.read();
        MultiSpec_1RuntimeMonitor.CipherInputStreamSpec_r1Event();
        return result;
    }

    public static int javax_crypto_CipherInputStream_read_1(javax.crypto.CipherInputStream recv, byte[] p0, int p1, int p2) throws Exception {
        int result = recv.read(p0, p1, p2);
        MultiSpec_1RuntimeMonitor.CipherInputStreamSpec_r2Event(p0, p1, p2);
        return result;
    }

    public static void javax_crypto_CipherInputStream_close(javax.crypto.CipherInputStream recv) throws Exception {
        recv.close();
        MultiSpec_1RuntimeMonitor.CipherInputStreamSpec_cl1Event();
    }

    public static void javax_crypto_CipherOutputStream_write(javax.crypto.CipherOutputStream recv, int p0) throws Exception {
        recv.write(p0);
        MultiSpec_1RuntimeMonitor.CipherOutputStreamSpec_w1Event();
    }

    public static void javax_crypto_CipherOutputStream_write_1(javax.crypto.CipherOutputStream recv, byte[] p0, int p1, int p2) throws Exception {
        recv.write(p0, p1, p2);
        MultiSpec_1RuntimeMonitor.CipherOutputStreamSpec_w2Event(p0, p1, p2);
    }

    public static void javax_crypto_CipherOutputStream_flush(javax.crypto.CipherOutputStream recv) throws Exception {
        recv.flush();
        MultiSpec_1RuntimeMonitor.CipherOutputStreamSpec_flEvent();
    }

    public static void javax_crypto_CipherOutputStream_close(javax.crypto.CipherOutputStream recv) throws Exception {
        recv.close();
        MultiSpec_1RuntimeMonitor.CipherOutputStreamSpec_clEvent();
    }

    public static javax.crypto.Cipher javax_crypto_Cipher_getInstance(java.lang.String p0) throws Exception {
        javax.crypto.Cipher result = javax.crypto.Cipher.getInstance(p0);
        MultiSpec_1RuntimeMonitor.CipherSpec_g1Event(p0, result);
        MultiSpec_1RuntimeMonitor.CipherSpec_g3Event(p0, result);
        return result;
    }

    public static javax.crypto.Cipher javax_crypto_Cipher_getInstance_1(java.lang.String p0, java.lang.String p1) throws Exception {
        javax.crypto.Cipher result = javax.crypto.Cipher.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.CipherSpec_g1Event(p0, result);
        MultiSpec_1RuntimeMonitor.CipherSpec_g3Event(p0, result);
        return result;
    }

    public static javax.crypto.Cipher javax_crypto_Cipher_getInstance_2(java.lang.String p0, java.security.Provider p1) throws Exception {
        javax.crypto.Cipher result = javax.crypto.Cipher.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.CipherSpec_g1Event(p0, result);
        MultiSpec_1RuntimeMonitor.CipherSpec_g3Event(p0, result);
        return result;
    }

    public static byte[] javax_crypto_Cipher_update(javax.crypto.Cipher recv, byte[] p0) throws Exception {
        byte[] result = recv.update(p0);
        MultiSpec_1RuntimeMonitor.CipherSpec_u1Event(p0, recv, result);
        return result;
    }

    public static byte[] javax_crypto_Cipher_update_1(javax.crypto.Cipher recv, byte[] p0, int p1, int p2) throws Exception {
        byte[] result = recv.update(p0, p1, p2);
        MultiSpec_1RuntimeMonitor.CipherSpec_u1Event(p0, recv, result);
        return result;
    }

    public static int javax_crypto_Cipher_update_2(javax.crypto.Cipher recv, byte[] p0, int p1, int p2, byte[] p3) throws Exception {
        int result = recv.update(p0, p1, p2, p3);
        MultiSpec_1RuntimeMonitor.CipherSpec_u3Event(p0, p1, p2, p3, recv);
        return result;
    }

    public static int javax_crypto_Cipher_update_3(javax.crypto.Cipher recv, byte[] p0, int p1, int p2, byte[] p3, int p4) throws Exception {
        int result = recv.update(p0, p1, p2, p3, p4);
        MultiSpec_1RuntimeMonitor.CipherSpec_u3Event(p0, p1, p2, p3, recv);
        return result;
    }

    public static int javax_crypto_Cipher_update_4(javax.crypto.Cipher recv, java.nio.ByteBuffer p0, java.nio.ByteBuffer p1) throws Exception {
        int result = recv.update(p0, p1);
        MultiSpec_1RuntimeMonitor.CipherSpec_u5Event(p0, p1, recv);
        return result;
    }

    public static byte[] javax_crypto_Cipher_wrap(javax.crypto.Cipher recv, java.security.Key p0) throws Exception {
        byte[] result = recv.wrap(p0);
        MultiSpec_1RuntimeMonitor.CipherSpec_wkb1Event(recv, result);
        return result;
    }

    public static byte[] javax_crypto_Cipher_doFinal(javax.crypto.Cipher recv) throws Exception {
        byte[] result = recv.doFinal();
        MultiSpec_1RuntimeMonitor.CipherSpec_f1Event(recv, result);
        return result;
    }

    public static byte[] javax_crypto_Cipher_doFinal_1(javax.crypto.Cipher recv, byte[] p0) throws Exception {
        byte[] result = recv.doFinal(p0);
        MultiSpec_1RuntimeMonitor.CipherSpec_f2Event(p0, recv, result);
        return result;
    }

    public static byte[] javax_crypto_Cipher_doFinal_2(javax.crypto.Cipher recv, byte[] p0, int p1, int p2) throws Exception {
        byte[] result = recv.doFinal(p0, p1, p2);
        MultiSpec_1RuntimeMonitor.CipherSpec_f2Event(p0, recv, result);
        return result;
    }

    public static int javax_crypto_Cipher_doFinal_3(javax.crypto.Cipher recv, byte[] p0, int p1) throws Exception {
        int result = recv.doFinal(p0, p1);
        MultiSpec_1RuntimeMonitor.CipherSpec_f3Event(p0, p1, recv);
        return result;
    }

    public static int javax_crypto_Cipher_doFinal_4(javax.crypto.Cipher recv, byte[] p0, int p1, int p2, byte[] p3) throws Exception {
        int result = recv.doFinal(p0, p1, p2, p3);
        MultiSpec_1RuntimeMonitor.CipherSpec_f5Event(p0, p1, p2, p3, recv);
        return result;
    }

    public static int javax_crypto_Cipher_doFinal_5(javax.crypto.Cipher recv, byte[] p0, int p1, int p2, byte[] p3, int p4) throws Exception {
        int result = recv.doFinal(p0, p1, p2, p3, p4);
        MultiSpec_1RuntimeMonitor.CipherSpec_f5Event(p0, p1, p2, p3, recv);
        return result;
    }

    public static int javax_crypto_Cipher_doFinal_6(javax.crypto.Cipher recv, java.nio.ByteBuffer p0, java.nio.ByteBuffer p1) throws Exception {
        int result = recv.doFinal(p0, p1);
        MultiSpec_1RuntimeMonitor.CipherSpec_f7Event(p0, p1, recv);
        return result;
    }

    public static javax.crypto.KeyGenerator javax_crypto_KeyGenerator_getInstance(java.lang.String p0) throws Exception {
        javax.crypto.KeyGenerator result = javax.crypto.KeyGenerator.getInstance(p0);
        MultiSpec_1RuntimeMonitor.KeyGeneratorSpec_g1Event(p0, result);
        MultiSpec_1RuntimeMonitor.KeyGeneratorSpec_g3Event(p0, result);
        return result;
    }

    public static javax.crypto.KeyGenerator javax_crypto_KeyGenerator_getInstance_1(java.lang.String p0, java.lang.String p1) throws Exception {
        javax.crypto.KeyGenerator result = javax.crypto.KeyGenerator.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.KeyGeneratorSpec_g2Event(p0, p1, result);
        return result;
    }

    public static javax.crypto.KeyGenerator javax_crypto_KeyGenerator_getInstance_2(java.lang.String p0, java.security.Provider p1) throws Exception {
        javax.crypto.KeyGenerator result = javax.crypto.KeyGenerator.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.KeyGeneratorSpec_g2Event(p0, p1, result);
        return result;
    }

    public static javax.crypto.SecretKey javax_crypto_KeyGenerator_generateKey(javax.crypto.KeyGenerator recv) throws Exception {
        javax.crypto.SecretKey result = recv.generateKey();
        MultiSpec_1RuntimeMonitor.KeyGeneratorSpec_gk1Event(recv, result);
        return result;
    }

    public static javax.net.ssl.KeyManagerFactory javax_net_ssl_KeyManagerFactory_getInstance(java.lang.String p0) throws Exception {
        javax.net.ssl.KeyManagerFactory result = javax.net.ssl.KeyManagerFactory.getInstance(p0);
        MultiSpec_1RuntimeMonitor.KeyManagerFactorySpec_g1Event(p0, result);
        MultiSpec_1RuntimeMonitor.KeyManagerFactorySpec_g3Event(p0, result);
        MultiSpec_1RuntimeMonitor.KeyManagerFactorySpec_g2Event(p0, result);
        return result;
    }

    public static javax.net.ssl.KeyManagerFactory javax_net_ssl_KeyManagerFactory_getInstance_1(java.lang.String p0, java.lang.String p1) throws Exception {
        javax.net.ssl.KeyManagerFactory result = javax.net.ssl.KeyManagerFactory.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.KeyManagerFactorySpec_g2Event(p0, result);
        return result;
    }

    public static javax.net.ssl.KeyManagerFactory javax_net_ssl_KeyManagerFactory_getInstance_2(java.lang.String p0, java.security.Provider p1) throws Exception {
        javax.net.ssl.KeyManagerFactory result = javax.net.ssl.KeyManagerFactory.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.KeyManagerFactorySpec_g2Event(p0, result);
        return result;
    }

    public static javax.net.ssl.KeyManager[] javax_net_ssl_KeyManagerFactory_getKeyManagers(javax.net.ssl.KeyManagerFactory recv) throws Exception {
        javax.net.ssl.KeyManager[] result = recv.getKeyManagers();
        MultiSpec_1RuntimeMonitor.KeyManagerFactorySpec_gkm1Event(recv, result);
        return result;
    }

    public static java.security.KeyPairGenerator java_security_KeyPairGenerator_getInstance(java.lang.String p0) throws Exception {
        java.security.KeyPairGenerator result = java.security.KeyPairGenerator.getInstance(p0);
        MultiSpec_1RuntimeMonitor.KeyPairGeneratorSpec_g1Event(p0, result);
        MultiSpec_1RuntimeMonitor.KeyPairGeneratorSpec_g3Event(p0, result);
        return result;
    }

    public static java.security.KeyPairGenerator java_security_KeyPairGenerator_getInstance_1(java.lang.String p0, java.lang.String p1) throws Exception {
        java.security.KeyPairGenerator result = java.security.KeyPairGenerator.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.KeyPairGeneratorSpec_g2Event(p0, p1, result);
        return result;
    }

    public static void java_security_KeyPairGenerator_initialize(java.security.KeyPairGenerator recv, int p0) throws Exception {
        recv.initialize(p0);
        MultiSpec_1RuntimeMonitor.KeyPairGeneratorSpec_init1Event(p0, recv);
        MultiSpec_1RuntimeMonitor.KeyPairGeneratorSpec_initErrorEvent(p0, recv);
    }

    public static void java_security_KeyPairGenerator_initialize_1(java.security.KeyPairGenerator recv, int p0, java.security.SecureRandom p1) throws Exception {
        recv.initialize(p0, p1);
        MultiSpec_1RuntimeMonitor.KeyPairGeneratorSpec_init2Event(p0, p1, recv);
    }

    public static void java_security_KeyPairGenerator_initialize_2(java.security.KeyPairGenerator recv, java.security.spec.AlgorithmParameterSpec p0) throws Exception {
        recv.initialize(p0);
        MultiSpec_1RuntimeMonitor.KeyPairGeneratorSpec_init3Event(p0, recv);
    }

    public static void java_security_KeyPairGenerator_initialize_3(java.security.KeyPairGenerator recv, java.security.spec.AlgorithmParameterSpec p0, java.security.SecureRandom p1) throws Exception {
        recv.initialize(p0, p1);
        MultiSpec_1RuntimeMonitor.KeyPairGeneratorSpec_init4Event(p0, p1, recv);
    }

    public static java.security.KeyPair java_security_KeyPairGenerator_generateKeyPair(java.security.KeyPairGenerator recv) throws Exception {
        java.security.KeyPair result = recv.generateKeyPair();
        MultiSpec_1RuntimeMonitor.KeyPairGeneratorSpec_genEvent(recv, result);
        return result;
    }

    public static java.security.PublicKey java_security_KeyPair_getPublic(java.security.KeyPair recv) throws Exception {
        java.security.PublicKey result = recv.getPublic();
        MultiSpec_1RuntimeMonitor.KeyPairSpec_gpuEvent(recv, result);
        return result;
    }

    public static java.security.PrivateKey java_security_KeyPair_getPrivate(java.security.KeyPair recv) throws Exception {
        java.security.PrivateKey result = recv.getPrivate();
        MultiSpec_1RuntimeMonitor.KeyPairSpec_gprEvent(recv, result);
        return result;
    }

    public static java.security.KeyStore java_security_KeyStore_getInstance(java.lang.String p0) throws Exception {
        java.security.KeyStore result = java.security.KeyStore.getInstance(p0);
        MultiSpec_1RuntimeMonitor.KeyStoreSpec_g1Event(p0, result);
        MultiSpec_1RuntimeMonitor.KeyStoreSpec_g2Event(p0, result);
        return result;
    }

    public static java.security.Key java_security_KeyStore_getKey(java.security.KeyStore recv, java.lang.String p0, char[] p1) throws Exception {
        java.security.Key result = recv.getKey(p0, p1);
        MultiSpec_1RuntimeMonitor.KeyStoreSpec_gk1Event(recv, result);
        return result;
    }

    public static javax.crypto.Mac javax_crypto_Mac_getInstance(java.lang.String p0) throws Exception {
        javax.crypto.Mac result = javax.crypto.Mac.getInstance(p0);
        MultiSpec_1RuntimeMonitor.MacSpec_g1Event(p0, result);
        MultiSpec_1RuntimeMonitor.MacSpec_g3Event(p0, result);
        return result;
    }

    public static javax.crypto.Mac javax_crypto_Mac_getInstance_1(java.lang.String p0, java.lang.String p1) throws Exception {
        javax.crypto.Mac result = javax.crypto.Mac.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.MacSpec_g2Event(p0, p1, result);
        return result;
    }

    public static void javax_crypto_Mac_init(javax.crypto.Mac recv, java.security.Key p0, java.security.spec.AlgorithmParameterSpec p1) throws Exception {
        recv.init(p0, p1);
        MultiSpec_1RuntimeMonitor.MacSpec_i2Event(p0, p1, recv);
    }

    public static void javax_crypto_Mac_update(javax.crypto.Mac recv, byte[] p0) throws Exception {
        recv.update(p0);
        MultiSpec_1RuntimeMonitor.MacSpec_uArrEvent(p0, recv);
    }

    public static void javax_crypto_Mac_update_1(javax.crypto.Mac recv, byte[] p0, int p1, int p2) throws Exception {
        recv.update(p0, p1, p2);
        MultiSpec_1RuntimeMonitor.MacSpec_uArrEvent(p0, recv);
    }

    public static void javax_crypto_Mac_update_2(javax.crypto.Mac recv, byte p0) throws Exception {
        recv.update(p0);
        MultiSpec_1RuntimeMonitor.MacSpec_uByteEvent(p0, recv);
    }

    public static void javax_crypto_Mac_update_3(javax.crypto.Mac recv, java.nio.ByteBuffer p0) throws Exception {
        recv.update(p0);
        MultiSpec_1RuntimeMonitor.MacSpec_uBufEvent(p0, recv);
    }

    public static byte[] javax_crypto_Mac_doFinal(javax.crypto.Mac recv) throws Exception {
        byte[] result = recv.doFinal();
        MultiSpec_1RuntimeMonitor.MacSpec_f1Event(recv, result);
        return result;
    }

    public static byte[] javax_crypto_Mac_doFinal_1(javax.crypto.Mac recv, byte[] p0) throws Exception {
        byte[] result = recv.doFinal(p0);
        MultiSpec_1RuntimeMonitor.MacSpec_f2Event(p0, recv, result);
        return result;
    }

    public static void javax_crypto_Mac_doFinal_2(javax.crypto.Mac recv, byte[] p0, int p1) throws Exception {
        recv.doFinal(p0, p1);
        MultiSpec_1RuntimeMonitor.MacSpec_f3Event(p0, p1);
    }

    public static java.security.MessageDigest java_security_MessageDigest_getInstance(java.lang.String p0) throws Exception {
        java.security.MessageDigest result = java.security.MessageDigest.getInstance(p0);
        MultiSpec_1RuntimeMonitor.MessageDigestSpec_g1Event(p0, result);
        MultiSpec_1RuntimeMonitor.MessageDigestSpec_g4Event(p0, result);
        return result;
    }

    public static java.security.MessageDigest java_security_MessageDigest_getInstance_1(java.lang.String p0, java.lang.String p1) throws Exception {
        java.security.MessageDigest result = java.security.MessageDigest.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.MessageDigestSpec_g2Event(p0, p1, result);
        return result;
    }

    public static java.security.MessageDigest java_security_MessageDigest_getInstance_2(java.lang.String p0, java.security.Provider p1) throws Exception {
        java.security.MessageDigest result = java.security.MessageDigest.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.MessageDigestSpec_g3Event(p0, p1, result);
        return result;
    }

    public static void java_security_MessageDigest_update(java.security.MessageDigest recv, byte p0) throws Exception {
        recv.update(p0);
        MultiSpec_1RuntimeMonitor.MessageDigestSpec_updateEvent(recv);
    }

    public static void java_security_MessageDigest_update_1(java.security.MessageDigest recv, byte[] p0, int p1, int p2) throws Exception {
        recv.update(p0, p1, p2);
        MultiSpec_1RuntimeMonitor.MessageDigestSpec_updateEvent(recv);
    }

    public static void java_security_MessageDigest_update_2(java.security.MessageDigest recv, byte[] p0) throws Exception {
        recv.update(p0);
        MultiSpec_1RuntimeMonitor.MessageDigestSpec_updateEvent(recv);
    }

    public static void java_security_MessageDigest_update_3(java.security.MessageDigest recv, java.nio.ByteBuffer p0) throws Exception {
        recv.update(p0);
        MultiSpec_1RuntimeMonitor.MessageDigestSpec_updateEvent(recv);
    }

    public static byte[] java_security_MessageDigest_digest(java.security.MessageDigest recv) throws Exception {
        byte[] result = recv.digest();
        MultiSpec_1RuntimeMonitor.MessageDigestSpec_d1Event(recv, result);
        return result;
    }

    public static byte[] java_security_MessageDigest_digest_1(java.security.MessageDigest recv, byte[] p0) throws Exception {
        byte[] result = recv.digest(p0);
        MultiSpec_1RuntimeMonitor.MessageDigestSpec_d2Event(recv, result);
        return result;
    }

    public static int java_security_MessageDigest_digest_2(java.security.MessageDigest recv, byte[] p0, int p1, int p2) throws Exception {
        int result = recv.digest(p0, p1, p2);
        MultiSpec_1RuntimeMonitor.MessageDigestSpec_d3Event(p0, p1, p2, recv);
        return result;
    }

    public static void javax_crypto_spec_PBEKeySpec_clearPassword(javax.crypto.spec.PBEKeySpec recv) throws Exception {
        recv.clearPassword();
        MultiSpec_1RuntimeMonitor.PBEKeySpecSpec_c2Event(recv);
    }

    public static java.lang.String java_lang_String_valueOf(java.lang.Object p0) throws Exception {
        java.lang.String result = java.lang.String.valueOf(p0);
        MultiSpec_1RuntimeMonitor.RandomStringPasswordSpec_voEvent(p0, result);
        return result;
    }

    public static char[] java_lang_String_toCharArray(java.lang.String recv) throws Exception {
        char[] result = recv.toCharArray();
        MultiSpec_1RuntimeMonitor.RandomStringPasswordSpec_gbEvent(recv, result);
        return result;
    }

    public static java.security.SecureRandom java_security_SecureRandom_getInstance(java.lang.String p0) throws Exception {
        java.security.SecureRandom result = java.security.SecureRandom.getInstance(p0);
        MultiSpec_1RuntimeMonitor.SecureRandomSpec_g1Event(p0, result);
        MultiSpec_1RuntimeMonitor.SecureRandomSpec_g2Event(p0, result);
        MultiSpec_1RuntimeMonitor.SecureRandomSpec_g4Event(p0, result);
        return result;
    }

    public static java.security.SecureRandom java_security_SecureRandom_getInstance_1(java.lang.String p0, java.lang.String p1) throws Exception {
        java.security.SecureRandom result = java.security.SecureRandom.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.SecureRandomSpec_g2Event(p0, result);
        MultiSpec_1RuntimeMonitor.SecureRandomSpec_g4Event(p0, result);
        return result;
    }

    public static java.security.SecureRandom java_security_SecureRandom_getInstance_2(java.lang.String p0, java.security.Provider p1) throws Exception {
        java.security.SecureRandom result = java.security.SecureRandom.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.SecureRandomSpec_g2Event(p0, result);
        MultiSpec_1RuntimeMonitor.SecureRandomSpec_g4Event(p0, result);
        return result;
    }

    public static java.security.SecureRandom java_security_SecureRandom_getInstanceStrong() throws Exception {
        java.security.SecureRandom result = java.security.SecureRandom.getInstanceStrong();
        MultiSpec_1RuntimeMonitor.SecureRandomSpec_g3Event(result);
        return result;
    }

    public static void java_security_SecureRandom_setSeed(java.security.SecureRandom recv, long p0) throws Exception {
        recv.setSeed(p0);
        MultiSpec_1RuntimeMonitor.SecureRandomSpec_setSeed1Event(recv);
    }

    public static void java_security_SecureRandom_setSeed_1(java.security.SecureRandom recv, byte[] p0) throws Exception {
        recv.setSeed(p0);
        MultiSpec_1RuntimeMonitor.SecureRandomSpec_setSeed2Event(p0, recv);
        MultiSpec_1RuntimeMonitor.SecureRandomSpec_setSeed3Event(p0, recv);
    }

    public static byte[] java_security_SecureRandom_generateSeed(java.security.SecureRandom recv, int p0) throws Exception {
        byte[] result = recv.generateSeed(p0);
        MultiSpec_1RuntimeMonitor.SecureRandomSpec_genSeedEvent(recv, result);
        return result;
    }

    public static java.security.Signature java_security_Signature_getInstance(java.lang.String p0) throws Exception {
        java.security.Signature result = java.security.Signature.getInstance(p0);
        MultiSpec_1RuntimeMonitor.SignatureSpec_g1Event(p0, result);
        MultiSpec_1RuntimeMonitor.SignatureSpec_g3Event(p0, result);
        return result;
    }

    public static java.security.Signature java_security_Signature_getInstance_1(java.lang.String p0, java.lang.String p1) throws Exception {
        java.security.Signature result = java.security.Signature.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.SignatureSpec_g2Event(p0, p1, result);
        return result;
    }

    public static boolean java_security_Signature_verify(java.security.Signature recv, byte[] p0) throws Exception {
        boolean result = recv.verify(p0);
        MultiSpec_1RuntimeMonitor.SignatureSpec_v1Event(p0, recv, result);
        return result;
    }

    public static boolean java_security_Signature_verify_1(java.security.Signature recv, byte[] p0, int p1, int p2) throws Exception {
        boolean result = recv.verify(p0, p1, p2);
        MultiSpec_1RuntimeMonitor.SignatureSpec_v2Event(p0, p1, p2, recv, result);
        return result;
    }

    public static javax.net.ssl.SSLContext javax_net_ssl_SSLContext_getInstance(java.lang.String p0) throws Exception {
        javax.net.ssl.SSLContext result = javax.net.ssl.SSLContext.getInstance(p0);
        MultiSpec_1RuntimeMonitor.SSLContextSpec_g1Event(p0, result);
        MultiSpec_1RuntimeMonitor.SSLContextSpec_unsafe_protocolEvent(p0, result);
        return result;
    }

    public static javax.net.ssl.SSLContext javax_net_ssl_SSLContext_getInstance_1(java.lang.String p0, java.lang.String p1) throws Exception {
        javax.net.ssl.SSLContext result = javax.net.ssl.SSLContext.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.SSLContextSpec_g2Event(p0, p1, result);
        return result;
    }

    public static void javax_net_ssl_SSLContext_init(javax.net.ssl.SSLContext recv, javax.net.ssl.KeyManager[] p0, javax.net.ssl.TrustManager[] p1, java.security.SecureRandom p2) throws Exception {
        recv.init(p0, p1, p2);
        MultiSpec_1RuntimeMonitor.SSLContextSpec_initEvent(recv, p0, p1, p2);
    }

    public static javax.net.ssl.TrustManagerFactory javax_net_ssl_TrustManagerFactory_getInstance(java.lang.String p0) throws Exception {
        javax.net.ssl.TrustManagerFactory result = javax.net.ssl.TrustManagerFactory.getInstance(p0);
        MultiSpec_1RuntimeMonitor.TrustManagerFactorySpec_g1Event(p0, result);
        MultiSpec_1RuntimeMonitor.TrustManagerFactorySpec_g3Event(p0, result);
        MultiSpec_1RuntimeMonitor.TrustManagerFactorySpec_g2Event(p0, result);
        return result;
    }

    public static javax.net.ssl.TrustManagerFactory javax_net_ssl_TrustManagerFactory_getInstance_1(java.lang.String p0, java.lang.String p1) throws Exception {
        javax.net.ssl.TrustManagerFactory result = javax.net.ssl.TrustManagerFactory.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.TrustManagerFactorySpec_g2Event(p0, result);
        return result;
    }

    public static javax.net.ssl.TrustManagerFactory javax_net_ssl_TrustManagerFactory_getInstance_2(java.lang.String p0, java.security.Provider p1) throws Exception {
        javax.net.ssl.TrustManagerFactory result = javax.net.ssl.TrustManagerFactory.getInstance(p0, p1);
        MultiSpec_1RuntimeMonitor.TrustManagerFactorySpec_g2Event(p0, result);
        return result;
    }

    public static javax.net.ssl.TrustManager[] javax_net_ssl_TrustManagerFactory_getTrustManagers(javax.net.ssl.TrustManagerFactory recv) throws Exception {
        javax.net.ssl.TrustManager[] result = recv.getTrustManagers();
        MultiSpec_1RuntimeMonitor.TrustManagerFactorySpec_gtm1Event(recv, result);
        return result;
    }

}
