@startuml
class MainActivity {
  #onCreate(Bundle)
  +showScreenMessageDigest(MenuItem)
  -showScreen(clazz: java.lang.Class)
}

note left of MainActivity::onCreate
<u>JAVA:</u>
setContentView(R.layout.<b>activity_main</b>);

<u>JIMPLE:</u>
virtualinvoke this.<br.unb.cic.cryptoapp.MainActivity: void setContentView(int)>(<color:royalBlue>2131492893</color>);

<u>R$layout.jimple</u>
<br.unb.cic.cryptoapp.R$layout: int <b>activity_main</b>> = <color:royalBlue>2131492893</color>;
end note





note right of MainActivity::showScreenMessageDigest
<u>JAVA:</u>
showScreen(MessageDigestActivity.class);

<u>JIMPLE:</u>
specialinvoke this.<br.unb.cic.cryptoapp.MainActivity: void showScreen(java.lang.Class)>(class "Lbr/unb/cic/cryptoapp/messagedigest/MessageDigestActivity;");
end note



note right of MainActivity::"showScreen(clazz: java.lang.Class)"
<u>JAVA:</u>
Intent intent = new Intent(this, clazz);
startActivity(intent);

<u>JIMPLE:</u>
$u2 := @parameter0: java.lang.Class;
intent = new android.content.Intent;
specialinvoke intent.<android.content.Intent: void <init>(android.content.Context,java.lang.Class)>(this, $u2);
virtualinvoke this.<br.unb.cic.cryptoapp.MainActivity: void startActivity(android.content.Intent)>(intent);
end note




note top of MainActivity
<u><b>activity_main</b>.xml</u>
<LinearLayout>
    <Button
        android:id="@+id/buttonMessageDigest"
        android:onClick="<b>showScreenMessageDigest</b>"
        android:text="@string/cteMessageDigest" />
</LinearLayout>
end note

@enduml
