"""
Static analysis data model for comprehensive Android application analysis.

This module provides structured data models for representing the complete
static analysis results from multiple analysis tools.
"""

from pydantic import ConfigDict, Field

# Direct imports - static.py should be imported after other domain modules
from rv_android_core.domain.classes import Classes
from rv_android_core.domain.components import Components
from rv_android_core.domain.window import Windows
from rv_android_core.domain.wtg import WindowTransitionGraph
from rv_android_core.util.validation import BaseValidatedModel
from rv_android_core.util.validation.decorators import validated_model


@validated_model(["classes", "windows", "wtg"])
class StaticAnalysisData(BaseValidatedModel):
    """
    Comprehensive data model for static analysis results from Android applications.

    This model aggregates analysis results from multiple static analysis tools
    (GESDA, GATOR, REACH) into a unified representation that supports both
    validation and serialization for downstream processing components.

    ### Architectural Role:
    - Serves as the primary data contract for static analysis output
    - Provides structured access to application structure, UI, and reachability data
    - Enables consistent data flow between analysis and experiment components
    - Supports validation of analysis completeness and data integrity

    ### Integration Points:
    - Generated by StaticAnalysisParser from raw tool outputs
    - Consumed by coverage analyzers for static-dynamic correlation
    - Used by experiment systems for comprehensive application understanding
    - Integrated with result storage and reporting pipelines

    ### Configuration:
    Inherits arbitrary_types_allowed=True from BaseValidatedModel for complex types.
    Enables validation of nested BaseValidatedModel instances.
    """

    model_config = ConfigDict(
        # Enable validation of nested Pydantic models
        arbitrary_types_allowed=True,
        # Accept existing BaseValidatedModel instances
        validate_default=True,
    )

    classes: Classes = Field(
        description="Application class structure and component information from GESDA analysis"
    )
    windows: Windows = Field(
        description="UI window and layout information extracted from static analysis"
    )
    wtg: WindowTransitionGraph = Field(
        description="Window transition graph representing application navigation flows from GATOR analysis"
    )
    components: Components = Field(
        default_factory=Components,
        description="Component data (Activities, Services, Receivers, Providers) with intent-filters, authorities, and MOP reachability",
    )
    complete: bool = Field(
        default=False,
        description=(
            "ADR-6 sentinel — True when the GATOR producer emitted "
            '"complete":true as the last top-level JSON field (signaling '
            "all sections finished writing) and the parser observed it. "
            "False when the file is from a pre-sentinel run, a partial "
            "(WTG-timeout) write, or a writer crash. Consumers requiring "
            "completeness (G_widget_reachability, sweep gates) MUST filter "
            "on this flag."
        ),
    )
