# rvandroid/tools/humanoid/tool.py
"""
Humanoid tool implementation with configuration support.
"""
from rvandroid.app import App
from rvandroid.commands.command import Command
from rvandroid.constants import ENV_HUMANOID_URL
from rvandroid.experiment.task.task_model import Task
from rvandroid.tools.configurable_tool import ConfigurableTool
from rvandroid.util import utils


class ToolSpec(ConfigurableTool):
    """
    Humanoid testing tool with configurable parameters.

    ### Architectural Decisions:
    - Extends ConfigurableTool for standardized configuration handling
    - Provides a unified interface to the Humanoid testing framework
    - Supports customization through configuration parameters

    ### Role in the System:
    - Integrates Humanoid Android testing tool into the RV-Android framework
    - Enables deep learning-guided testing with configurable parameters
    - Provides consistent execution interface aligned with other tools
    """

    def __init__(self):
        """Initialize the Humanoid tool with default configuration."""
        super().__init__(
            "humanoid",
            "Humanoid explores Android apps like human by using deep learning "
            "techniques to borrow experiences from app usage traces generated by human.",
            "com.android.commands.humanoid"
        )

        # Default configuration
        self.config = {
            "humanoid_url": "127.0.0.1:50405",
            "policy": "dfs_greedy"
        }

    def configure_tool_specific(self, config):
        """Configure Humanoid-specific parameters."""
        # Update parameters if specified
        if "humanoid_url" in config:
            self.config["humanoid_url"] = config["humanoid_url"]

        if "policy" in config:
            self.config["policy"] = config["policy"]

    def execute_tool_specific_logic(self, task: Task, app: App):
        """Execute Humanoid with the configured parameters."""
        self.logger.info(f"Running Humanoid on {app.name}")

        # Get Humanoid URL from config or environment
        humanoid_url = utils.get_env_or_default(
            ENV_HUMANOID_URL,
            self.config["humanoid_url"]
        )

        # Execute Humanoid through DroidBot
        with open(task.result.trace_file, "wb") as trace:
            exec_cmd = Command("droidbot", [
                "-d",
                "emulator-5554",
                "-a",
                app.path,
                "-humanoid",
                humanoid_url,
                "-policy",
                self.config["policy"],
                "-is_emulator",
            ], task.config.timeout)

            exec_cmd.invoke(stdout=trace)
