package br.unb.cic.rvsec.crysl.core.calibration;

/**
 * What kind of route produced a target's value, and therefore whether the target can fail.
 *
 * <p>This enum exists because two of the eight targets were once written so that the gate could not
 * fail: pairing was routed through the component's own pairing rule, and the {@code MapOfMonitor}
 * census through the AST proxy the component implements (RISK-006, D-18). A target routed through
 * the instrument restates the instrument; it goes green by construction and the green reads exactly
 * like a real one.
 *
 * <p>The classification is therefore data on every target and printed beside every verdict. It
 * costs one enum and it is the difference between "eight independently measured targets" and a
 * claim this change could not survive.
 */
public enum RouteClass {

    /**
     * A separate program that computes the quantity without using any of the component's code —
     * the {@code Census.java}, {@code Binding.java} and {@code V3Fresh.java} probes of
     * {@code docs/handoff/20260824_arnes_adjudicacao/}, or a raw-text census with no parser at all.
     */
    INDEPENDENT_PROBE,

    /**
     * A committed artifact the component does not produce — the {@code disposition} column of
     * {@code order_alphabet_map.csv}, or a hand-authored mapping table. It is independent of the
     * component and it is human judgement, which is a different weakness from circularity and is
     * labelled separately so a reader can weigh it.
     */
    COMMITTED_ARTIFACT,

    /**
     * An artifact regenerated by the production toolchain and then read — the
     * {@code rv-monitor-generator} pass whose {@code MultiSpec_1RuntimeMonitor.java} is the real
     * oracle of whether a specification indexes. It costs a generation pass and it is the only
     * version of that check that can come out wrong.
     */
    REGENERATED_ARTIFACT,

    /**
     * The route is a rule the component itself implements. <strong>Not a calibration.</strong> A
     * target in this class is published as a labelled self-consistency check and is never counted
     * among the calibration targets (D-18); {@link CalibrationGate} refuses to treat it as one.
     */
    SAME_ALGORITHM_RESTATEMENT;

    /** Whether a target on this route can contradict the component and therefore calibrates it. */
    public boolean calibrates() {
        return this != SAME_ALGORITHM_RESTATEMENT;
    }
}
