# rvandroid/llm/data_structures.py
"""Core data structures for the LLM messages."""

from dataclasses import dataclass
from enum import Enum
from typing import List, Dict, Any, Optional, Union


class LLMRole(Enum):
    """Role of a message in a conversation."""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


@dataclass
class LLMTextContent:
    """Text content in an LLM message."""
    text: str


@dataclass
class LLMImageContent:
    """Image content in an LLM message."""
    url: str
    detail: Optional[str] = "auto"


# Union type for different content types
LLMContentType = Union[LLMTextContent, LLMImageContent]



@dataclass
class LLMMessage:
    """
    Standard message format for Model Context Protocol.
    
    Represents a structured message in a conversation between the system,
    user, assistant, or tools. Messages can contain multiple content items
    of different types (text, images, etc.).
    """
    role: LLMRole
    content: List[LLMContentType]
    name: Optional[str] = None
    # TODO deprecated
    tool_calls: Optional[List[Dict[str, Any]]] = None
    tool_call_id: Optional[str] = None

    def total_chars(self):
        cont = 0
        for item in self.content:
            if isinstance(item, LLMTextContent):
                cont += len(item.text)
        return cont

    def __str__(self):
        return f"LLMMessage(role={self.role}, content={self.content})"

    def get_text_content(self) -> str:
        """
        Get combined text content from the message.
        
        Returns:
            String combining all text content items
        """
        text_parts = []
        for item in self.content:
            if isinstance(item, LLMTextContent):
                text_parts.append(item.text)
        return "\n".join(text_parts)

    def to_message_dict(self) -> Dict[str, Any]:
        items = [{
            "type": "text",
            "text": self.get_text_content()
        }]
        for item in self.content:
            if isinstance(item, LLMImageContent):
                items.append({
                    "type": "image",
                    "url": item.url
                })
        return {
            "role": self.role.value,
            "content": items
        }


# @dataclass
# class MCPAction:
#     id: int
#     params: Dict[str, Any]
#     explanation: Optional[str] = None


@dataclass
class LLMResponse:
    # Capture and store the full model response along with granular performance diagnostics:
    # - message.content: The generated text response from the model. This is the core output returned to the user.
    # - done_reason: Explains why the generation stopped. Common values include 'stop' (natural stop), 'length' (token limit reached),
    #                or custom stop sequences. Useful for determining whether the output was truncated or ended cleanly.
    # - total_duration: Total elapsed time (in milliseconds or seconds, depending on the API) from the beginning of the request to
    #                   the receipt of the full response. Includes all stages: model load, prompt evaluation, and token generation.
    # - load_duration: Time taken to load the model into memory if it was not already active. High values here can indicate cold starts,
    #                  which may be optimized by warming up the model in advance or keeping it resident.
    # - input_tokens: The number of tokens in the input prompt processed by the model. Important for estimating prompt cost and
    #                      understanding how much context is being consumed before generation begins.
    # - input_tokens_duration: Time spent (in ms or s) processing the input prompt tokens. High values may indicate a long or complex prompt.
    # - output_tokens: The number of tokens generated by the model in its output. Combined with input_tokens, this helps track
    #               total token usage for billing or quota enforcement.
    # - output_tokens_duration: Time spent generating output tokens. Can be used to measure generation speed and model throughput.
    #                           It is the inference time.

    content: str
    role = LLMRole.ASSISTANT
    done = True
    done_reason = "stop"
    total_duration = 0
    load_duration = 0
    input_tokens = 0
    input_tokens_duration = 0
    output_tokens = 0
    output_tokens_duration = 0

    def total_chars(self):
        return len(self.content)

# deprecated
# @dataclass
# class MCPConfiguration_OLD:
#     """
#     Configuration parameters for language models using MCP.
#
#     Provides a standardized set of parameters for controlling
#     language model behavior, regardless of the specific model
#     implementation.
#     """
#     temperature: float = 0.7
#     max_tokens: Optional[int] = None
#     top_p: float = 1.0
#     frequency_penalty: float = 0.0
#     presence_penalty: float = 0.0
#     stop: Optional[List[str]] = None
#     model_type: str = "ollama"
#     model_name: str = "llama3.2:3b"
#
#     def to_dict(self) -> Dict[str, Any]:
#         """
#         Convert configuration to dictionary.
#
#         Returns:
#             Dictionary representation of configuration
#         """
#         return {
#             "temperature": self.temperature,
#             "max_tokens": self.max_tokens,
#             "top_p": self.top_p,
#             "frequency_penalty": self.frequency_penalty,
#             "presence_penalty": self.presence_penalty,
#             "stop": self.stop,
#             "model_type": self.model_type,
#             "model_name": self.model_name
#         }
#
#     @classmethod
#     def from_dict(cls, data: Dict[str, Any]) -> 'MCPConfiguration':
#         """
#         Create configuration from dictionary.
#
#         Args:
#             data: Dictionary containing configuration data
#
#         Returns:
#             MCPConfiguration instance
#         """
#         return cls(
#             temperature=data.get("temperature", 0.7),
#             max_tokens=data.get("max_tokens"),
#             top_p=data.get("top_p", 1.0),
#             frequency_penalty=data.get("frequency_penalty", 0.0),
#             presence_penalty=data.get("presence_penalty", 0.0),
#             stop=data.get("stop"),
#             model_type=data.get("model_type", "ollama"),
#             model_name=data.get("model_name", "llama3.2:3b")
#         )