"""
Short Term Memory for RVAgent - Screen-scoped memory.

Implementation EXATA do plano com process isolation support.
Gerencia memória de curto prazo das interações LLM para a tela atual.
"""

import time
from datetime import datetime
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field

from rv_android_core.util.logging.manager import LoggingManager
from rv_android_core.util.error.error_handler import ErrorHandler

from ..constants import RVAgentConstants


@dataclass
class Iteration:
    """
    Representa uma iteração única de interação com a tela atual.

    Representa uma chamada ao LLM e as ações geradas.
    ADAPTADO para cliente (sem dependencies server-side).
    """

    state_hash: str
    activity: str
    timestamp: datetime = field(default_factory=datetime.now)
    actions: List[Dict] = field(default_factory=list)
    llm_reasoning: str = ""
    execution_results: List[Dict] = field(default_factory=list)

    def add_action(self, action_dict: Dict[str, Any]) -> None:
        """Adiciona ação à iteração."""
        self.actions.append(action_dict)

    def add_execution_result(self, result_dict: Dict[str, Any]) -> None:
        """Add execution result for this iteration."""
        self.execution_results.append(result_dict)

    def format_for_template(self) -> str:
        """
        Formata informação da iteração para template com representação compacta.

        Otimização Phase 0 validada: redução token count ~85%.
        """
        if not self.actions:
            return ""

        action_texts = []
        for i, action in enumerate(self.actions):
            action_text = action.get("element_id", action.get("action_type", "unknown"))
            coordinates = action.get("coordinates", [])

            if coordinates:
                action_text += f" at ({coordinates[0]}, {coordinates[1]})"

            # Add result if available
            if i < len(self.execution_results):
                result = self.execution_results[i]
                status = "✅" if result.get("success", False) else "❌"
                action_text = f"{status} {action_text}"

            action_texts.append(action_text)

        return ", ".join(action_texts)

    def get_success_rate(self) -> float:
        """Calculate success rate for this iteration."""
        if not self.execution_results:
            return 0.0

        successful = sum(
            1 for result in self.execution_results if result.get("success", False)
        )
        return successful / len(self.execution_results)


class ShortTermMemory:
    """
    Gerencia memória de curto prazo das interações LLM para a tela atual.

    PROCESSO SUBPROCESS ISOLADO:
    - LoggingManager.get_instance() com instância própria do subprocess
    - ErrorHandler decorators disponíveis (instância própria)
    - GeneratedAction disponível via rv-android-core
    - Memória local para estado do cliente

    Target: br.unb.cic.cryptoapp - Screen-scoped memory management
    """

    def __init__(
        self, max_iterations: int = RVAgentConstants.MAX_SHORT_TERM_ITERATIONS
    ):
        """Initialize short term memory with process isolation support."""

        # Process isolation - LoggingManager com instância própria
        logging_manager = LoggingManager.get_instance()
        self.logger = logging_manager.get_logger(
            "rv_agent.memory.short_term", {"component": "ShortTermMemory"}
        )

        # ErrorHandler decorators disponíveis no subprocess
        self.error_handler = ErrorHandler.get_instance()

        self.current_activity: Optional[str] = None
        self.iterations: List[Iteration] = []
        self.max_iterations = max_iterations

        self.logger.info(f" ShortTermMemory initialized (max: {max_iterations})")

    def record_iteration(
        self, state: Dict[str, Any], actions: List[Dict], llm_reasoning: str = ""
    ) -> None:
        """
        Registra uma nova iteração com error handling cliente.

        CLIENTE: NÃO usa StateEntry constants (independente de servidor).

        Args:
            state: Current UI state dictionary
            actions: List of actions generated by LLM
            llm_reasoning: LLM reasoning text for this iteration
        """
        try:
            activity = state.get("activity", "unknown")
            state_hash = state.get("hash_screen", "unknown")

            # Activity changed - clear memory
            if activity != self.current_activity:
                self.logger.info(
                    f" Activity changed: {self.current_activity} → {activity}"
                )
                self.clear()
                self.current_activity = activity

            iteration = Iteration(
                state_hash=state_hash, activity=activity, llm_reasoning=llm_reasoning
            )

            for action in actions:
                iteration.add_action(action)

            self.iterations.insert(0, iteration)  # Most recent first

            if len(self.iterations) > self.max_iterations:
                removed = self.iterations[self.max_iterations :]
                self.iterations = self.iterations[: self.max_iterations]
                self.logger.debug(f" Removed {len(removed)} old iterations")

            self.logger.debug(
                f" Iteration recorded: {len(actions)} actions, "
                f"total iterations: {len(self.iterations)}"
            )

        except Exception as e:
            # CLIENTE error handling - log e continue
            self.logger.error(f" Failed to record iteration: {e}")

    def record_execution_results(self, results: List[Dict[str, Any]]) -> None:
        """
        Record execution results for the most recent iteration.

        Args:
            results: List of execution results from DeviceInterface
        """
        try:
            if not self.iterations:
                self.logger.warning(" No iterations to record results for")
                return

            latest_iteration = self.iterations[0]
            for result in results:
                latest_iteration.add_execution_result(result)

            success_rate = latest_iteration.get_success_rate()
            self.logger.debug(
                f" Execution results recorded: "
                f"{len(results)} results, {success_rate:.1%} success rate"
            )

        except Exception as e:
            self.logger.error(f" Failed to record execution results: {e}")

    def get_recent_actions_summary(self, count: int = 3) -> str:
        """
        Get summary of recent actions for LLM context.

        Args:
            count: Number of recent iterations to include

        Returns:
            Formatted string for LLM prompt
        """
        try:
            if not self.iterations:
                return "No recent actions."

            recent_iterations = self.iterations[:count]
            formatted_iterations = []

            for i, iteration in enumerate(recent_iterations):
                iteration_text = iteration.format_for_template()
                if iteration_text:
                    age = "just now" if i == 0 else f"{i} iterations ago"
                    formatted_iterations.append(f"• {age}: {iteration_text}")

            if not formatted_iterations:
                return "Recent actions had no results."

            return "\n".join(formatted_iterations)

        except Exception as e:
            self.logger.error(f" Recent actions summary failed: {e}")
            return f"Error retrieving recent actions: {e}"

    def get_current_screen_context(self) -> Dict[str, Any]:
        """
        Get context about current screen based on short term memory.

        Returns comprehensive information for ReAct reasoning.
        """
        try:
            if not self.iterations:
                return {
                    "screen_status": "new",
                    "interaction_count": 0,
                    "recent_success_rate": 0.0,
                    "suggested_strategy": "explore_elements",
                }

            # Calculate recent success rate
            recent_successes = []
            for iteration in self.iterations[:3]:  # Last 3 iterations
                if iteration.execution_results:
                    recent_successes.append(iteration.get_success_rate())

            avg_success_rate = (
                sum(recent_successes) / len(recent_successes)
                if recent_successes
                else 0.0
            )

            # Determine screen exploration status
            total_actions = sum(len(iter.actions) for iter in self.iterations)

            if len(self.iterations) >= 3 and avg_success_rate < 0.3:
                strategy = "try_different_approach"
            elif total_actions < 5:
                strategy = "continue_exploration"
            elif avg_success_rate > 0.7:
                strategy = "deepen_exploration"
            else:
                strategy = "balanced_exploration"

            return {
                "screen_status": (
                    "explored" if len(self.iterations) >= 2 else "partially_explored"
                ),
                "interaction_count": len(self.iterations),
                "total_actions_tried": total_actions,
                "recent_success_rate": avg_success_rate,
                "suggested_strategy": strategy,
                "current_activity": self.current_activity,
            }

        except Exception as e:
            self.logger.error(f" Screen context calculation failed: {e}")
            return {"error": str(e), "screen_status": "unknown"}

    def format_for_template(self, count: int = 3) -> str:
        """
        Formata últimas iterações para template LLM.

        OTIMIZAÇÃO Phase 0: Context window management para LLM calls.

        Args:
            count: Number of recent iterations to include

        Returns:
            Formatted text for LLM prompt
        """
        try:
            summary = self.get_recent_actions_summary(count)
            context = self.get_current_screen_context()

            if summary == "No recent actions.":
                return "This is a new screen - no previous actions attempted."

            # Build comprehensive but concise context
            context_parts = [f"Recent actions on this screen:\n{summary}"]

            # Add strategic context
            strategy = context.get("suggested_strategy", "explore_elements")
            success_rate = context.get("recent_success_rate", 0.0)

            if strategy == "try_different_approach":
                context_parts.append(
                    f"⚠️ Recent success rate is low ({success_rate:.1%}). Try different elements or actions."
                )
            elif strategy == "deepen_exploration":
                context_parts.append(
                    f"✅ Recent success rate is good ({success_rate:.1%}). Continue exploring this area."
                )

            return "\n".join(context_parts)

        except Exception as e:
            self.logger.error(f" Template formatting failed: {e}")
            return f"Error formatting memory: {e}"

    def clear(self) -> None:
        """Limpa memória de curto prazo."""
        cleared_count = len(self.iterations)
        self.iterations.clear()

        self.logger.debug(f" Short term memory cleared ({cleared_count} iterations)")

    def get_statistics(self) -> Dict[str, Any]:
        """Get short term memory statistics."""
        try:
            if not self.iterations:
                return {
                    "iteration_count": 0,
                    "current_activity": self.current_activity,
                    "memory_status": "empty",
                }

            # Calculate comprehensive statistics
            total_actions = sum(len(iter.actions) for iter in self.iterations)
            total_results = sum(len(iter.execution_results) for iter in self.iterations)

            success_rates = [
                iter.get_success_rate()
                for iter in self.iterations
                if iter.execution_results
            ]
            avg_success_rate = (
                sum(success_rates) / len(success_rates) if success_rates else 0.0
            )

            # Recent activity
            latest_iteration = self.iterations[0] if self.iterations else None

            return {
                "iteration_count": len(self.iterations),
                "current_activity": self.current_activity,
                "total_actions_generated": total_actions,
                "total_execution_results": total_results,
                "average_success_rate": avg_success_rate,
                "memory_utilization": f"{len(self.iterations)}/{self.max_iterations}",
                "latest_iteration": (
                    {
                        "timestamp": (
                            latest_iteration.timestamp.isoformat()
                            if latest_iteration
                            else None
                        ),
                        "action_count": (
                            len(latest_iteration.actions) if latest_iteration else 0
                        ),
                        "success_rate": (
                            latest_iteration.get_success_rate()
                            if latest_iteration
                            else 0.0
                        ),
                    }
                    if latest_iteration
                    else None
                ),
            }

        except Exception as e:
            self.logger.error(f" Statistics calculation failed: {e}")
            return {"error": str(e)}
